### ISSUE TITLE
更新0.1.0版本之后所有实体都不可用

### ISSUE THREAD

**Issue by FaintGhost** [banto6/haier#12]
**问题描述**
更新之后所有实体变为不可用，日志有多条报错。
家里有两台海尔的空调，一台卡萨帝冰箱和一台卡萨帝洗衣机，目前只有两个空调能正常识别。0.1.0之前的版本空调可以正常控制。
另外想请问大佬是否有计划把空调设备内的实体整合为HA的climate实体？感谢大佬！

**环境信息:**
 - Homeassistant版本: 2023.7.1

**日志信息**
```
Logger: homeassistant.components.switch
Source: custom_components/haier/__init__.py:146
Integration: 开关 ([documentation](https://www.home-assistant.io/integrations/switch), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+switch%22))
First occurred: 10:38:03 (1 occurrences)
Last logged: 10:38:03

Error while setting up haier platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 353, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/haier/switch.py", line 20, in async_setup_entry
    await async_register_entity(hass, entry, async_add_entities, register, 'switch')
  File "/config/custom_components/haier/__init__.py", line 146, in async_register_entity
    if cfg[CONF_FILTER_TYPE] == 'exclude' and spec['key'] in cfg[CONF_TARGET_ENTITIES]:
       ~~~^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

```
Logger: homeassistant.components.binary_sensor
Source: custom_components/haier/__init__.py:146
Integration: 二元传感器 ([documentation](https://www.home-assistant.io/integrations/binary_sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+binary_sensor%22))
First occurred: 10:38:03 (1 occurrences)
Last logged: 10:38:03

Error while setting up haier platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 353, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/haier/binary_sensor.py", line 19, in async_setup_entry
    await async_register_entity(hass, entry, async_add_entities, register, 'binary_sensors')
  File "/config/custom_components/haier/__init__.py", line 146, in async_register_entity
    if cfg[CONF_FILTER_TYPE] == 'exclude' and spec['key'] in cfg[CONF_TARGET_ENTITIES]:
       ~~~^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

```
Logger: homeassistant.components.number
Source: custom_components/haier/__init__.py:146
Integration: 数值输入器 ([documentation](https://www.home-assistant.io/integrations/number), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+number%22))
First occurred: 10:38:03 (1 occurrences)
Last logged: 10:38:03

Error while setting up haier platform for number
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 353, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/haier/number.py", line 18, in async_setup_entry
    await async_register_entity(hass, entry, async_add_entities, register, 'numbers')
  File "/config/custom_components/haier/__init__.py", line 146, in async_register_entity
    if cfg[CONF_FILTER_TYPE] == 'exclude' and spec['key'] in cfg[CONF_TARGET_ENTITIES]:
       ~~~^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

```
Logger: homeassistant.components.select
Source: custom_components/haier/__init__.py:146
Integration: 选择器 ([documentation](https://www.home-assistant.io/integrations/select), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+select%22))
First occurred: 10:38:03 (1 occurrences)
Last logged: 10:38:03

Error while setting up haier platform for select
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 353, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/haier/select.py", line 18, in async_setup_entry
    await async_register_entity(hass, entry, async_add_entities, register, 'selects')
  File "/config/custom_components/haier/__init__.py", line 146, in async_register_entity
    if cfg[CONF_FILTER_TYPE] == 'exclude' and spec['key'] in cfg[CONF_TARGET_ENTITIES]:
       ~~~^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

```
Logger: custom_components.haier
Source: custom_components/haier/haier.py:181
Integration: Haier ([documentation](https://github.com/banto6/haier), [issues](https://github.com/banto6/haier/issues))
First occurred: 10:38:01 (2 occurrences)
Last logged: 10:38:03

设备[04FA83FA81E5]初始化失败
设备[DC330D6383E7]初始化失败
Traceback (most recent call last):
  File "/config/custom_components/haier/__init__.py", line 42, in async_setup_entry
    specs = await client.get_hardware_config(device.wifi_type)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/haier.py", line 181, in get_hardware_config
    raise HaierClientException('获取配置文件失败')
custom_components.haier.haier.HaierClientException: 获取配置文件失败
```

```
Logger: custom_components.haier.haier
Source: custom_components/haier/haier.py:179
Integration: Haier ([documentation](https://github.com/banto6/haier), [issues](https://github.com/banto6/haier/issues))
First occurred: 10:38:01 (2 occurrences)
Last logged: 10:38:03

获取配置信息失败, wifi_type: 111c120024000810040100318001150000000000000000000000000000000000, response: {"status": "1", "data": null, "total": 0}
获取配置信息失败, wifi_type: 111c120024000810010200618003654100000000000061800376410000010000, response: {"status": "1", "data": null, "total": 0}
```

**Comment by banto6** [comment]
问题已修复

**Comment by banto6** [comment]
新增climate实体可以提供一下空调对应的wifi_type，我看能不能做一个通用组件，wifi_type参数可在日志中`Device Info`部分找到。

**Comment by FaintGhost** [comment]
> 新增climate实体可以提供一下空调对应的wifi_type，我看能不能做一个通用组件，wifi_type参数可在日志中`Device Info`部分找到。

抱歉回复您迟了，不知道为什么微软把github的邮件判断为垃圾邮件了，刚刚更新了master分支的代码设备控制功能已经恢复正常了。

wifi_type我在error日志中找到了如下：
```
Logger: custom_components.haier.haier
Source: custom_components/haier/haier.py:179
Integration: Haier ([documentation](https://github.com/banto6/haier), [issues](https://github.com/banto6/haier/issues))
First occurred: 21:59:51 (2 occurrences)
Last logged: 21:59:54

获取配置信息失败, wifi_type: 111c120024000810040100318001150000000000000000000000000000000000, response: {"status": "1", "data": null, "total": 0}
获取配置信息失败, wifi_type: 111c120024000810010200618003654100000000000061800376410000010000, response: {"status": "1", "data": null, "total": 0}
```

对应的两个设备DEBUG信息如下，再次感谢大佬的辛苦工作！
```
2023-07-08 04:21:39.302 DEBUG (MainThread) [custom_components.haier.coordinator] 设备[18A7F1AAD312]已获取到最新状态数据: {"intelligenceStatus": "false", "humidificationStatus": "false", "silentSleepStatus": "false", "electricHeatingStatus": "false", "ch2oValue": "0", "rapidMode": "false", "energySavePeriod": "20", "specialMode": "0", "10degreeHeatingStatus": "false", "ch2oCleaningStatus": "false", "humanSensingStatus": "0", "outdoorPM2p5Value": "0", "acType": "0", "lightStatus": "false", "totalCleaningTime": "81", "errCode": "", "totalElectricityUsed": "145686", "sensingResult": "0", "tempUnit": "1", "lockStatus": "false", "selfCleaningStatus": "false", "airQuality": "0", "operationModeHK": "0", "operationMode": "1", "co2Value": "0", "targetTemperature": "27.00", "vocValue": "0", "localFilterChangeFlag": "false", "energySavingStatus": "false", "freshAirStatus": "false", "windDirectionVertical": "0", "onOffStatus": "false", "halfDegreeSettingStatus": "false", "echoStatus": "false", "outdoorTemperature": "28.00", "pm2p5Level": "0", "indoorPM2p5Value": "8", "pmvStatus": "false", "muteStatus": "false", "healthMode": "false", "ErrAckFlag": "false", "pm2p5CleaningStatus": "false", "targetHumidity": "30", "indoorTemperature": "29.50", "windSpeed": "1", "heatAccumulationStatus": "false", "opSrc": "1", "screenDisplayStatus": "true", "windDirectionHorizontal": "0", "indoorHumidity": "0"}
2023-07-08 04:21:39.678 DEBUG (MainThread) [custom_components.haier.coordinator] 设备[18A7F146A350]已获取到最新状态数据: {"intelligenceStatus": "false", "humidificationStatus": "false", "silentSleepStatus": "false", "electricHeatingStatus": "false", "ch2oValue": "0", "rapidMode": "false", "energySavePeriod": "15", "specialMode": "0", "10degreeHeatingStatus": "false", "ch2oCleaningStatus": "false", "humanSensingStatus": "0", "outdoorPM2p5Value": "0", "acType": "0", "lightStatus": "false", "totalCleaningTime": "0", "errCode": "", "totalElectricityUsed": "0", "sensingResult": "0", "tempUnit": "1", "lockStatus": "false", "selfCleaningStatus": "false", "airQuality": "0", "operationModeHK": "0", "operationMode": "6", "co2Value": "0", "targetTemperature": "26.00", "vocValue": "0", "localFilterChangeFlag": "false", "energySavingStatus": "false", "freshAirStatus": "false", "windDirectionVertical": "0", "onOffStatus": "false", "halfDegreeSettingStatus": "false", "echoStatus": "false", "outdoorTemperature": "28.00", "pm2p5Level": "0", "indoorPM2p5Value": "0", "pmvStatus": "false", "muteStatus": "false", "healthMode": "false", "ErrAckFlag": "false", "pm2p5CleaningStatus": "false", "targetHumidity": "30", "indoorTemperature": "32.00", "windSpeed": "2", "heatAccumulationStatus": "false", "opSrc": "1", "screenDisplayStatus": "true", "windDirectionHorizontal": "7", "indoorHumidity": "0"}
```

**Comment by banto6** [comment]
error日志中的wifi_type是无法识别的设备，应该查看`Device Info`部分的日志

**Comment by FaintGhost** [comment]
> error日志中的wifi_type是无法识别的设备，应该查看`Device Info`部分的日志

抱歉大佬不知道是不是方法不对，我实在是没找到Device Info这个字段的日志（已经开了DEBUG模式）。

**Comment by banto6** [comment]
试试这个呢 

配置 > 系统 > 日志 > 加载完整日志

**Comment by FaintGhost** [comment]
> 试试这个呢
> 
> 配置 > 系统 > 日志 > 加载完整日志

找到了！感谢大佬！
```
2023-07-08 03:59:50.197 DEBUG (MainThread) [custom_components.haier] Device Info: {'_raw_data': {'deviceId': '18A7F146A350', 'deviceName': '挂式空调', 'deviceType': '0201201G', 'online': True, 'permissions': [{'auth': {'control': True, 'set': True, 'view': True}, 'authType': 'owner'}, {'auth': {'control': True, 'set': False, 'view': True}, 'authType': 'home'}], 'productCodeT': 'AAABNH001', 'productNameT': 'KFR-35GW/05SNA81U1套机', 'totalPermission': {'control': True, 'set': True, 'view': True}, 'wifiType': '2008610800820324021200118007264200000000000000000000000000000040'}}
```
```
2023-07-08 03:59:51.461 DEBUG (MainThread) [custom_components.haier] Device Info: {'_raw_data': {'deviceId': '04FA83FA81E5', 'deviceName': '我家卡萨帝洗衣机', 'deviceType': '04001023', 'online': True, 'permissions': [{'auth': {'control': True, 'set': True, 'view': True}, 'authType': 'owner'}, {'auth': {'control': True, 'set': False, 'view': True}, 'authType': 'home'}], 'productCodeT': 'CB0JR000X', 'productNameT': 'C601 30RG', 'totalPermission': {'control': True, 'set': True, 'view': True}, 'wifiType': '111c120024000810040100318001150000000000000000000000000000000000'}}
```
