### ISSUE TITLE
登录失败，返回错误:接口异常：用户不合法

### ISSUE THREAD

**Issue by fhleo** [banto6/haier#139]
**问题描述**
集成设置错误，通过日志查看错误原因为用户不合法

**环境信息:**
 - Homeassistant版本: [e.g. 2024.5.4]
 - APP版本：1.0.0

**错误日志**
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 575, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/__init__.py", line 25, in async_setup_entry
    devices = await client.get_devices()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/core/client.py", line 57, in get_devices
    self._assert_response_successful(content)
  File "/config/custom_components/haier/core/client.py", line 313, in _assert_response_successful
    raise HaierClientException('接口返回异常: ' + resp['retInfo'])
custom_components.haier.core.client.HaierClientException: 接口返回异常: 用户不合法

**Comment by banto6** [comment]
更新token试试

**Comment by fhleo** [comment]
已经做过以下尝试：
1.集成中删除从新添加。
2.重新更新token与ID

**Comment by loftyyang** [comment]
> 更新token试试

怎么更细token啊
