### ISSUE TITLE
集成设置失败，设置中可在实体筛选周昂可以读取到实体，单无法添加实体

### ISSUE THREAD

**Issue by fhleo** [banto6/haier#140]
**前言**
集成设置失败

**问题描述**
设置中可在实体筛选周昂可以读取到实体，单无法添加实体

**环境信息:**
 - Homeassistant版本: [e.g. 2024.5.4]

**设备信息**
.storage/haier/`目录下没有找到device_设备ID.json

**错误日志**
2024-05-29 22:07:00.489 DEBUG (MainThread) [custom_components.haier.core.client] Device Info: {'deviceId': '*****', 'deviceName': '洗衣机', 'deviceType': '0500119g', 'online': False, 'permissions': [{'auth': {'control': True, 'set': True, 'view': True}, 'authType': 'owner'}], 'productCodeT': 'CEAAHA003', 'productNameT': 'C1 HD10LZ6CLU1', 'totalPermission': {'control': True, 'set': True, 'view': True}, 'wifiType': '201c51890c31c308050100218001914d00000000000000000000000000000040'}
2024-05-29 22:07:00.785 DEBUG (MainThread) [custom_components.haier] 共获取到2个设备
2024-05-29 22:07:00.864 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Haier: f2e9d6 for haier
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 575, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/__init__.py", line 33, in async_setup_entry
    await store.async_save(json.dumps(await client.get_digital_model(device.id), ensure_ascii=False))
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/core/client.py", line 87, in get_digital_model
    return json.loads(content['detailInfo'][deviceId])['attributes']
                      ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'C8934643BC0D'

**抓包信息**
附件为小程序抓取/shadow/v1/devdigitalmodels信息
[Uploading 118_Full.txt…]()

**Comment by banto6** [comment]
用master分支代码

**Comment by fhleo** [comment]
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 575, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/__init__.py", line 47, in async_setup_entry
    'product_code': device.product_code,
                    ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/core/device.py", line 35, in product_code
    return self._raw_data['productCodeT']
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'productCodeT'

**Comment by banto6** [comment]
重新使用master试试
