### ISSUE TITLE
1.1.0 token报错

### ISSUE THREAD

**Issue by dwxiayi** [banto6/haier#142]
**前言**
- 请自行搜索历史issues是否存在相同问题
- 尽量按格式填写Issues模版中的必要信息，没有这些信息就算提交了也解决不了任何问题。

**问题描述**

**环境信息:**
 - Homeassistant版本: [2023.12.4]

**设备信息**
若是设备无法识别或控制错误则此项**必填**，没有设备信息可能会被直接关闭不做处理。

设备信息可在`.storage/haier/`目录下找到，文件格式为`device_设备ID.json`，上传文件时可将文件名和文件内容中的`设备ID`替换为任意值以保护个人隐私。

设备ID可开启debug模式后可在`Device Info`部分的日志中找到。日志可在`配置 > 系统 > 日志 > 加载完整日志`中查看。

**错误日志**
若是运行报错或操控异常则日志**必填**，没有日志可能会被直接关闭不做处理。
ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Haier: f967ba for haierTraceback (most recent call last):
  File "/opt/hass/lib/python3.12/site-packages/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hass/hassconf/custom_components/haier/__init__.py", line 26, in async_setup_entry
    await try_update_token(hass, entry)
  File "/opt/hass/hassconf/custom_components/haier/__init__.py", line 106, in try_update_token
    token_info = await client.refresh_token(cfg.refresh_token)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hass/hassconf/custom_components/haier/core/client.py", line 86, in refresh_token
    self._assert_response_successful(content)
  File "/opt/hass/hassconf/custom_components/haier/core/client.py", line 400, in _assert_response_successful
    raise HaierClientException('接口返回异常: ' + resp['retInfo'])
custom_components.haier.core.client.HaierClientException: 接口返回异常: refreshToken不允许为空
2024-05-30 22:52:04.414 WARNING (MainThread) [custom_components.haier.config_flow] 接口返回异常: 授权异常或失败
2024-05-30 22:54:59.028 WARNING (MainThread) [custom_components.haier.config_flow] 接口返回异常: 授权异常或失败

**Comment by banto6** [comment]
看更新日志
