### ISSUE TITLE
使用1.10版本加载集成时没有显示设备和实体

### ISSUE THREAD

**Issue by fannagi** [banto6/haier#144]
**问题描述**
使用最新的1.10版本，clientID和refresh token都填写好，登陆后加载一直没有出现相关的实体和设备信息。状态为设置失败。
目前抓包是使用PC微信小程序，不与HA系统相同网络下抓的包，是与此原因相关吗？

**环境信息:**
 - Homeassistant版本: 2023.9.2[e.g. 2023.6.2]

**设备信息**
若是设备无法识别或控制错误则此项**必填**，没有设备信息可能会被直接关闭不做处理。

设备信息可在`.storage/haier/`目录下找到，文件格式为`device_设备ID.json`，上传文件时可将文件名和文件内容中的`设备ID`替换为任意值以保护个人隐私。

设备ID可开启debug模式后可在`Device Info`部分的日志中找到。日志可在`配置 > 系统 > 日志 > 加载完整日志`中查看。

**错误日志**

2024-06-02 16:12:17.921 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Haier: *********** for haier
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/__init__.py", line 34, in async_setup_entry
    devices = await client.get_devices()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/core/client.py", line 121, in get_devices
    self._assert_response_successful(content)
  File "/config/custom_components/haier/core/client.py", line 400, in _assert_response_successful
    raise HaierClientException('接口返回异常: ' + resp['retInfo'])
custom_components.haier.core.client.HaierClientException: 接口返回异常: Token不是由此应用创建，未通过token验证。

**Comment by banto6** [comment]
client_id跟refresh_token不匹配

**Comment by fannagi** [comment]
确实是少复制一位了，尴尬。感谢大佬
