### ISSUE TITLE
就一台海尔空调，能识别，但无法添加实体

### ISSUE THREAD

**Issue by sulon007** [banto6/haier#15]
Unknown error occurred
添加实体时报错如上，期待解决

**Comment by banto6** [comment]
请提供错误日志

**Comment by sulon007** [comment]
添加中枢，提交时，homeassistant的日志如下：
2023-07-10 11:08:23.085 ERROR (MainThread) [custom_components.haier.haier] 获取配置信息失败, wifi_type: 00000000000000008080000000041410, response: {"status": "1", "data": null, "total": 0}
2023-07-10 11:08:23.101 ERROR (MainThread) [custom_components.haier] 设备[DC330D32EF96]初始化失败
Traceback (most recent call last):
  File "/config/custom_components/haier/__init__.py", line 44, in async_setup_entry
    specs = await client.get_hardware_config(device.wifi_type)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/haier.py", line 181, in get_hardware_config
    raise HaierClientException('获取配置文件失败')
custom_components.haier.haier.HaierClientException: 获取配置文件失败

-------------------------------------------------------------------------------------------

选项--实体筛选--提交时，homeassistant会报下面的错误：
2023-07-10 11:11:13.340 ERROR (MainThread) [custom_components.haier.haier] 获取配置信息失败, wifi_type: 00000000000000008080000000041410, response: {"status": "1", "data": null, "total": 0}
2023-07-10 11:11:13.355 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 242, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 297, in async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 393, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/config_flow.py", line 151, in async_step_entity_device_selector
    return await self.async_step_entity_filter()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/config_flow.py", line 184, in async_step_entity_filter
    spec_resp = await client.get_hardware_config(target_device['wifi_type'])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/haier.py", line 181, in get_hardware_config
    raise HaierClientException('获取配置文件失败')
custom_components.haier.haier.HaierClientException: 获取配置文件失败

**Comment by banto6** [comment]
提示`获取配置文件失败`表示设备跟当前API不兼容，暂时没有解决方案，目前正在考虑更换API，可以关注一下后续更新。

**Comment by TeCHiScy** [comment]
> 提示`获取配置文件失败`表示设备跟当前API不兼容，暂时没有解决方案，目前正在考虑更换API，可以关注一下后续更新。

目前用的 API 感觉和海尔智家 App 不是同一套，想了解下目前用的这套 API 是从其他什么 App 抓的么？

**Comment by banto6** [comment]
> > 提示`获取配置文件失败`表示设备跟当前API不兼容，暂时没有解决方案，目前正在考虑更换API，可以关注一下后续更新。
> 
> 抓了海尔智家 App 的包看了下，目前用的 API 感觉和它不是同一套，想了解下目前用的这套 API 是从其他什么 App 抓的么？

从海尔调试工具中抓取的，现在貌似已经没办法下载到这个软件了
