### ISSUE TITLE
设置失败，KeyError: 'deviceType' 出现这个报错  id和refreshtoken都没有错

### ISSUE THREAD

**Issue by redhatme** [banto6/haier#164]
2024-07-06 09:31:03.358 WARNING (MainThread) [custom_components.haier.core.client] Device TA80BJYW7FTNANBFDU76A0DRSBI8MOE5 get digital model fail. response: {"retCode": "00000", "retInfo": "操作成功", "detailInfo": {}}
2024-07-06 09:31:03.360 DEBUG (MainThread) [custom_components.haier.core.client] Device Info: {'deviceId': '2C37C5B05762FFFE0E570A04', 'deviceName': '右下键', 'deviceRole': '3', 'deviceRoleType': '从设备', 'deviceType': '100110I4', 'online': True, 'parentDeviceId': '2C37C5B057623EFFFE0E570A', 'permissions': [{'auth': {'control': True, 'set': True, 'view': True}, 'authType': 'owner'}], 'productCodeT': 'NE07XJD02', 'productNameT': '智能开关CET-12DWN6-U5', 'totalPermission': {'control': True, 'set': True, 'view': True}, 'wifiType': '201c80c70c50031c101103f7dd40b6000000ec03f6b908ac6923bbf0e5b4a640'}
2024-07-06 09:31:03.550 DEBUG (MainThread) [custom_components.haier.core.client] Device Info: {'deviceId': '2C37C5B05762FFFE0E570A03', 'deviceName': '左下键', 'deviceRole': '3', 'deviceRoleType': '从设备', 'deviceType': '100110I4', 'online': True, 'parentDeviceId': '2C37C5B057623EFFFE0E570A', 'permissions': [{'auth': {'control': True, 'set': True, 'view': True}, 'authType': 'owner'}], 'productCodeT': 'NE07XJD02', 'productNameT': '智能开关CET-12DWN6-U5', 'totalPermission': {'control': True, 'set': True, 'view': True}, 'wifiType': '201c80c70c50031c101103f7dd40b6000000ec03f6b908ac6923bbf0e5b4a640'}
2024-07-06 09:31:03.780 DEBUG (MainThread) [custom_components.haier.core.client] Device Info: {'deviceId': '2C37C5B070363EFFFE0988B2', 'deviceName': '门口智能开关', 'deviceRole': '4', 'deviceRoleType': '从设备', 'deviceType': '1401102J', 'online': True, 'parentDeviceId': '2C37C5B07036', 'permissions': [{'auth': {'control': True, 'set': True, 'view': True}, 'authType': 'owner'}], 'productCodeT': 'NE07XHD02', 'productNameT': '智能开关CET-12DWN4-U5', 'totalPermission': {'control': True, 'set': True, 'view': True}, 'wifiType': '201c80c70c50031c1411ee1382da77000000f366d47f6678be2acbc3de457a40'}
2024-07-06 09:31:03.991 DEBUG (MainThread) [custom_components.haier.core.client] Device Info: {'deviceId': 'D937C5C295', 'deviceName': '扫地机器人', 'deviceType': '2700201E', 'online': True, 'permissions': [{'auth': {'control': True, 'set': True, 'view': True}, 'authType': 'owner'}], 'productCodeT': 'F5512A000', 'productNameT': '扫地机JH69U1', 'totalPermission': {'control': True, 'set': True, 'view': True}, 'wifiType': '2054a0cc113541202702db4722b49d0000000ae32d3f75dc10890337f6047940'}
2024-07-06 09:31:04.186 DEBUG (MainThread) [custom_components.haier.core.client] Device Info: {'deviceId': '9GIEX1TUA3JSG9J4D3162KOG6RFYUN7U', 'deviceName': '9GIEX1TUA3JSG9J4D3162KOG6RFYUN7U', 'online': False, 'permissions': [{'auth': {'control': True, 'set': True, 'view': True}, 'authType': 'home'}], 'totalPermission': {'control': True, 'set': True, 'view': True}, 'wifiType': '2082f4b3457817734cbc053da91f2120e582f4b3457817734cbc053da91f2160'}
2024-07-06 09:31:04.333 WARNING (MainThread) [custom_components.haier.core.client] Device 9GIEX1TUA3JSG9J4D3162KOG6RFYUN7U get digital model fail. response: {"retCode": "00000", "retInfo": "操作成功", "detailInfo": {}}
2024-07-06 09:31:04.334 DEBUG (MainThread) [custom_components.haier.core.client] Device Info: {'deviceId': '2C37C5B057623EFFFE08B4E3', 'deviceName': '门口智能开关', 'deviceRole': '4', 'deviceRoleType': '主设备', 'deviceType': '1401102J', 'online': True, 'parentDeviceId': '2C37C5B05762', 'permissions': [{'auth': {'control': True, 'set': True, 'view': True}, 'authType': 'owner'}], 'productCodeT': 'NE07XHD02', 'productNameT': '智能开关CET-12DWN4-U5', 'totalPermission': {'control': True, 'set': True, 'view': True}, 'wifiType': '201c80c70c50031c1411ee1382da77000000f366d47f6678be2acbc3de457a40'}
2024-07-06 09:31:04.547 DEBUG (MainThread) [custom_components.haier.core.client] Device Info: {'deviceId': '2C37C5B0576257FFFED9681D', 'deviceName': '卷帘', 'deviceRole': '4', 'deviceRoleType': '从设备', 'deviceType': '1401101Q', 'online': True, 'parentDeviceId': '2C37C5B05762', 'permissions': [{'auth': {'control': True, 'set': True, 'view': True}, 'authType': 'owner'}], 'productCodeT': 'NE07X0D02', 'productNameT': '智能开关HET-H2LWN4-U5', 'totalPermission': {'control': True, 'set': True, 'view': True}, 'wifiType': '201c80c70c50031c1411b881f47af70000009341f3190bec34100587987c5840'}
2024-07-06 09:31:04.778 DEBUG (MainThread) [custom_components.haier.core.client] Device Info: {'deviceId': '04E2294E20F0', 'deviceName': '门锁', 'deviceType': '1100200U', 'online': True, 'permissions': [{'auth': {'control': True, 'set': True, 'view': True}, 'authType': 'owner'}], 'productCodeT': 'NF06Y0000', 'productNameT': '智能门锁HFH-68E-R 曜石黑', 'totalPermission': {'control': True, 'set': True, 'view': True}, 'wifiType': '201c80c70c50031c1102ac92bdcbde0000009411fbc076679109ee07b8b56a40'}
2024-07-06 09:31:05.326 DEBUG (MainThread) [custom_components.haier] 共获取到92个设备
2024-07-06 09:31:06.566 WARNING (MainThread) [custom_components.haier.core.client] Device U5B0JTQWWX7BMAHZ0D60R0RNCM9H9K8O get digital model fail. response: {"retCode": "00000", "retInfo": "操作成功", "detailInfo": {}}
2024-07-06 09:31:06.568 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Haier -  for haier
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 586, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/__init__.py", line 46, in async_setup_entry
    'type': device.type,
            ^^^^^^^^^^^
  File "/config/custom_components/haier/core/device.py", line 32, in type
    return self._raw_data['deviceType']
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'deviceType'

**Comment by banto6** [comment]
试试master分支代码

**Comment by redhatme** [comment]
好的，我测试下，感谢回复

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年07月06日 12:26 |
| 收件人 | banto6/haier ***@***.***> |
| 抄送人 | redhatme ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [banto6/haier] 设置失败，KeyError: 'deviceType' 出现这个报错 id和refreshtoken都没有错 (Issue #164) |

试试master分支代码

**Comment by redhatme** [comment]
> 试试master分支代码
可以正常使用了。感谢大佬
