### ISSUE TITLE
无法登录，（用的电脑版本黄鸟一直用这个抓）重新抓包多次也不行，不知道我那个地方出错，我升级了最新集成（v1.1.1）后出现token失效，上个版本集成正常

### ISSUE THREAD

**Issue by Awe7** [banto6/haier#176]
**问题描述**
无法登录，（用的电脑版本黄鸟一直用这个抓）重新抓包多次也不行，不知道我那个地方出错，我升级了最新集成（v1.1.1）后出现token失效，上个版本集成正常

**环境信息:**
Core
2024.7.4
Supervisor
2024.06.2
Operating System
12.4
Frontend
20240710.0

https://uws.haier.net/gmsWS/wsag/assign

{
  "token": "******",
  "clientId": "*******"
}

**错误日志**
日志记录器: custom_components.haier.config_flow
来源: custom_components/haier/config_flow.py:45
集成: Haier ([文档](https://github.com/banto6/haier), [问题](https://github.com/banto6/haier/issues))
首次出现: 20:46:51 (7 次总计出现)
上次记录: 20:58:11

接口返回异常: 授权异常或失败

**Comment by Awe7** [comment]
已解决，需要抓  refreshtoken  详情看  佬 帖  https://bbs.hassbian.com/thread-25297-1-1.html

**Comment by fsayyeah** [comment]
大佬们你好，我按照上面教程成功抓取了refreshtoken，依然无法登录，能帮忙看看是什么情况吗？

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 575, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/__init__.py", line 59, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(entry, SUPPORTED_PLATFORMS)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1939, in async_forward_entry_setups
    await integration.async_get_platforms(platforms)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1090, in async_get_platforms
    if platform := self._get_platform_cached_or_raise(platform_name):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1181, in _get_platform_cached_or_raise
    raise ModuleNotFoundError(
ModuleNotFoundError: Platform haier.binary_sensor not found

**Comment by Awe7** [comment]
如果出现token 失败，最新升级了其他token，检查token 是否获取的正确。 正确的话卸载重装试下。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月2日(周一) 晚上8:15
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [banto6/haier] 无法登录，（用的电脑版本黄鸟一直用这个抓）重新抓包多次也不行，不知道我那个地方出错，我升级了最新集成（v1.1.1）后出现token失效，上个版本集成正常 (Issue #176)




 
大佬们你好，我按照上面教程成功抓取了refreshtoken，依然无法登录，能帮忙看看是什么情况吗？
 
Traceback (most recent call last):
 File "/usr/src/homeassistant/homeassistant/config_entries.py", line 575, in async_setup
 result = await component.async_setup_entry(hass, self)
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/config/custom_components/haier/init.py", line 59, in async_setup_entry
 await hass.config_entries.async_forward_entry_setups(entry, SUPPORTED_PLATFORMS)
 File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1939, in async_forward_entry_setups
 await integration.async_get_platforms(platforms)
 File "/usr/src/homeassistant/homeassistant/loader.py", line 1090, in async_get_platforms
 if platform := self._get_platform_cached_or_raise(platform_name):
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/usr/src/homeassistant/homeassistant/loader.py", line 1181, in _get_platform_cached_or_raise
 raise ModuleNotFoundError(
 ModuleNotFoundError: Platform haier.binary_sensor not found

**Comment by danniod** [comment]
<img width="427" alt="image" src="https://github.com/user-attachments/assets/66b5688c-67c5-4372-a8f3-115e3ec131b7" />
帮助能找到仓库，配置token半天一直失败，为啥不更到README

**Comment by banto6** [comment]
see https://github.com/banto6/haier/issues/186#issuecomment-2667308799
