### ISSUE TITLE
小程序抓包成功但问题是小程序不支持全部智能设备

### ISSUE THREAD

**Issue by weiweis99** [banto6/haier#179]
问题描述：
小程序不支持卡萨帝中央空调LVIP-RFTS71CXS-D(YH) 导致抓取成功后集成显示无实体设备 实际上app中有四个设备 小程序中不显示设备
信息：卡萨帝中央空调LVIP-RFTS71CXS-D(YH)
错误日志：2024-09-22 19:50:08.321 警告 (SyncWorker_0) [homeassistant.loader] 我们发现自定义集成 haier 尚未经过 Home Assistant 测试。此组件可能会导致稳定性问题，如果您遇到 Home Assistant 问题，请务必禁用它
2024-09-22 19:50:08.322 警告 (SyncWorker_0) [homeassistant.loader] 我们发现自定义集成 hacs 尚未经过 Home Assistant 测试。此组件可能会导致稳定性问题，如果您遇到 Home Assistant 问题，请务必禁用它
2024-09-22 19:50:08.323 警告 (SyncWorker_0) [homeassistant.loader] 我们发现自定义集成 xiaomi_miot 尚未经过 Home Assistant 测试。此组件可能会导致稳定性问题，如果您遇到 Home Assistant 问题，请务必禁用它
2024-09-22 20:20:40.803 错误（MainThread）[homeassistant.config_entries] 设置条目 Haier 时出错 - haier 的 15666317026
Traceback（最近一次调用最后一次）：
文件“/usr/src/homeassistant/homeassistant/config_entries.py”，第 604 行，在 async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
文件“/config/custom_components/haier/ init .py”，第 34 行，在 async_setup_entry
devices = await client.get_devices()
^^^^^^^^^^^^^^^^^^^^^^^^^^
文件“/config/custom_components/haier/core/client.py”，第 121 行，在 get_devices
self._assert_response_successful(content)
文件“/config/custom_components/haier/core/client.py”，第 400 行，在 _assert_response_successful 中
引发 HaierClientException('接口返回异常: ' + resp['retInfo'])
custom_components.haier.core.client.HaierClientException: 接口返回异常: Token 不是此时应用创建，未通过token验证
2024-09-22 20:21:36.919 ERROR (MainThread) [homeassistant.config_entries] 设置条目 Haier 时出错: 15666317026 for Haier
Traceback (最近一次调用最后):
文件“/usr/src/homeassistant/homeassistant/config_entries.py”, 第 604 行, 在 async_setup 中
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
文件“/config/custom_components/haier/ init .py”, 第 34 行, 在 async_setup_entry 中
devices = await client.get_devices()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
文件“/config/custom_components/haier/core/client.py”, 第 121 行, 在 get_devices 中
self._assert_response_successful(content)
文件“/config/custom_components/haier/core/client.py”, 第 400 行, 在_assert_response_successful
引发 HaierClientException('接口返回异常: ' + resp['retInfo'])
custom_components.haier.core.client.HaierClientException: 接口返回异常:Token不是由此应用创建，未通过token验证
2024-09-22 20:21:41.428 错误（主线程）[homeassistant.config_entries] 设置条目 Haier 时出错：haier 的 15666317026
回溯（最近一次调用最后一次）：
文件“/usr/src/homeassistant/homeassistant/config_entries.py”，第 604 行，在 async_setup 中，
结果 = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
文件“/config/custom_components/haier/ init .py”，第 34 行，在 async_setup_entry 中，
设备 = await client.get_devices()
^^^^^^^^^^^^^^^^^^^^^^^^^^
文件“/config/custom_components/haier/core/client.py”，第 121 行，在 get_devices
self._assert_response_successful(content)
文件“/config/custom_components/haier/core/client.py”，第 400 行，在 _assert_response_successful 中
引发 HaierClientException('接口返回异常: ' + resp['retInfo'])
custom_components.haier.core.client.HaierClientException: 接口返回异常: Token 不是此时应用创建，未通过token验证
2024-09-22 20:32:44.523 警告 (MainThread) [custom_components.haier.config_flow] 接口返回异常: 授权异常或失败
2024-09-22 20:33:00.374 警告 (MainThread) [custom_components.haier.config_flow] 接口返回异常: 授权异常或失败
2024-09-22 20:40:49.799 警告 (MainThread) [custom_components.haier.config_flow] 接口返回异常: 授权异常或失败
2024-09-22 20:41:16.299错误（MainThread）[homeassistant.config_entries]为海尔回溯设置条目海尔 - 15666317026
（最近一次调用最后一次）时出错：
文件“/usr/src/homeassistant/homeassistant/config_entries.py”，第604行，在async_setup
结果=等待component.async_setup_entry（hass，self）
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
文件“/config/custom_components/haier/ init .py”, 第 34 行, 位于 async_setup_entry
devices = await client.get_devices()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
文件“/config/custom_components/haier/core/client.py”, 第 121 行, 位于 get_devices
self._assert_response_successful(content)
文件“/config/custom_components/haier/core/client.py”, 第 400 行, 位于 _assert_response_successful
raise HaierClientException('接口返回异常: ' + resp['retInfo'])
custom_components.haier.core.client.HaierClientException: 返回接口异常: Token不是由此应用创建，未通过token验证
2024-09-22 20:41:24.814 ERROR (MainThread) [homeassistant.config_entries] 为haier Traceback设置条目Haier - 15666317026
(最近一次调用)时出错：
文件“/usr/src/homeassistant/homeassistant/config_entries.py”，第604行， async_setup
结果 = 等待组件.async_setup_entry(hass,自我）
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
文件“/config/custom_components/haier/ init .py”，第 34 行，在 async_setup_entry 中
devices = wait client.get_devices()
^^^^^^^^^^^^^^^^^^^^^^^^^^^
文件 "/config/custom_components/haier/core/client.py",第 121 行，在 get_devices
self._assert_response_successful(content)
文件“/config/custom_components/haier/core/client.py”中，第 400 行，在 _assert_response_successful 中
引发 HaierClientException('接口返回异常: ' + resp['retInfo'])
custom_components .haier.core.client.HaierClientException: 接口返回异常: Token不是由此应用创建，未通过token验证
2024-09-22 20:56:04.480 ERROR (MainThread) [homeassistant.config_entries] 设置条目 Haier 时出错 - 15666317026为海尔
回溯（最近一次调用最后一次）：
文件“/usr/src/homeassistant/homeassistant/config_entries.py”，第 604 行，在 async_setup
结果 = await component.async_setup_entry（hass，self）
^^^^^^^^^^^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
文件“/config/custom_components/haier/ init .py”，行34，在 async_setup_entry
devices = await client.get_devices()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
文件“/config/custom_components/haier/core/client .py”，第 121 行，在 get_devices
self._assert_response_successful(content)
文件中“/config/custom_components/haier/core/client.py”，第 400 行，在 _assert_response_successful 中
引发 HaierClientException('接口返回异常: ' + resp['retInfo'])
custom_components.haier.core.client.HaierClientException: 接口返回异常: Token不是由此应用创建，未通过token验证

**Comment by weiweis99** [comment]
2024-09-22 19:50:08.321 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration haier which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-09-22 19:50:08.322 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-09-22 19:50:08.323 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration xiaomi_miot which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-09-22 20:20:40.803 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Haier - 15666317026 for haier
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/__init__.py", line 34, in async_setup_entry
    devices = await client.get_devices()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/core/client.py", line 121, in get_devices
    self._assert_response_successful(content)
  File "/config/custom_components/haier/core/client.py", line 400, in _assert_response_successful
    raise HaierClientException('接口返回异常: ' + resp['retInfo'])
custom_components.haier.core.client.HaierClientException: 接口返回异常: Token不是由此应用创建，未通过token验证
2024-09-22 20:21:36.919 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Haier: 15666317026 for haier
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/__init__.py", line 34, in async_setup_entry
    devices = await client.get_devices()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/core/client.py", line 121, in get_devices
    self._assert_response_successful(content)
  File "/config/custom_components/haier/core/client.py", line 400, in _assert_response_successful
    raise HaierClientException('接口返回异常: ' + resp['retInfo'])
custom_components.haier.core.client.HaierClientException: 接口返回异常: Token不是由此应用创建，未通过token验证
2024-09-22 20:21:41.428 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Haier: 15666317026 for haier
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/__init__.py", line 34, in async_setup_entry
    devices = await client.get_devices()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/core/client.py", line 121, in get_devices
    self._assert_response_successful(content)
  File "/config/custom_components/haier/core/client.py", line 400, in _assert_response_successful
    raise HaierClientException('接口返回异常: ' + resp['retInfo'])
custom_components.haier.core.client.HaierClientException: 接口返回异常: Token不是由此应用创建，未通过token验证
2024-09-22 20:32:44.523 WARNING (MainThread) [custom_components.haier.config_flow] 接口返回异常: 授权异常或失败
2024-09-22 20:33:00.374 WARNING (MainThread) [custom_components.haier.config_flow] 接口返回异常: 授权异常或失败
2024-09-22 20:40:49.799 WARNING (MainThread) [custom_components.haier.config_flow] 接口返回异常: 授权异常或失败
2024-09-22 20:41:16.299 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Haier - 15666317026 for haier
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/__init__.py", line 34, in async_setup_entry
    devices = await client.get_devices()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/core/client.py", line 121, in get_devices
    self._assert_response_successful(content)
  File "/config/custom_components/haier/core/client.py", line 400, in _assert_response_successful
    raise HaierClientException('接口返回异常: ' + resp['retInfo'])
custom_components.haier.core.client.HaierClientException: 接口返回异常: Token不是由此应用创建，未通过token验证
2024-09-22 20:41:24.814 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Haier - 15666317026 for haier
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/__init__.py", line 34, in async_setup_entry
    devices = await client.get_devices()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/core/client.py", line 121, in get_devices
    self._assert_response_successful(content)
  File "/config/custom_components/haier/core/client.py", line 400, in _assert_response_successful
    raise HaierClientException('接口返回异常: ' + resp['retInfo'])
custom_components.haier.core.client.HaierClientException: 接口返回异常: Token不是由此应用创建，未通过token验证
2024-09-22 20:56:04.480 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Haier - 15666317026 for haier
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/__init__.py", line 34, in async_setup_entry
    devices = await client.get_devices()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/core/client.py", line 121, in get_devices
    self._assert_response_successful(content)
  File "/config/custom_components/haier/core/client.py", line 400, in _assert_response_successful
    raise HaierClientException('接口返回异常: ' + resp['retInfo'])
custom_components.haier.core.client.HaierClientException: 接口返回异常: Token不是由此应用创建，未通过token验证

**Comment by weiweis99** [comment]
卡萨帝中央空调LVIP-RFTS71CXS-D(YH)
![9167024a95e0e09fc1dd2cebbcc2a1e](https://github.com/user-attachments/assets/59ab8bc0-040d-48f1-a155-08a4df654a9c)
![微信截图_20240922210016](https://github.com/user-attachments/assets/7cd3c9f4-20e5-4fa6-8008-913978534852)

**Comment by weiweis99** [comment]
已解决
