### ISSUE TITLE
洗衣机在筛选中能看到，但是无生成任何实体

### ISSUE THREAD

**Issue by FenixJun** [banto6/haier#18]
**问题描述**
洗衣机在筛选中能看到，但是无生成任何实体

**环境信息:**
 - Homeassistant版本:  2023.6.2

**日志信息**
此错误来自自定义集成。

Logger: custom_components.haier
Source: custom_components/haier/haier.py:181
Integration: Haier (documentation, issues)
First occurred: 23:49:32 (2 occurrences)
Last logged: 23:50:49

设备[DC330D89F953]初始化失败
Traceback (most recent call last):
  File "/config/custom_components/haier/__init__.py", line 43, in async_setup_entry
    specs = await client.get_hardware_config(device.wifi_type)
  File "/config/custom_components/haier/haier.py", line 181, in get_hardware_config
    raise HaierClientException('获取配置文件失败')
custom_components.haier.haier.HaierClientException: 获取配置文件失败

**Comment by banto6** [comment]
请提供一下设备信息

以下信息开启debug模式后可在`Device Info`部分的日志中找到。日志可在`配置 > 系统 > 日志 > 加载完整日志`中查看。
```
deviceType:
productCodeT:
productNameT:
wifiType:
```

**Comment by FenixJun** [comment]
2023-07-21 23:54:48.405 ERROR (MainThread) [custom_components.haier.haier] 获取配置信息失败, wifi_type: 111c12002400081005010021800111000000e400000000000000000000000000, response: {"status": "1", "data": null, "total": 0}
2023-07-21 23:54:48.413 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
resp = await request_handler(request)
File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
result = await result
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 241, in post
return await super().post(request, flow_id)
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
result = await method(view, request, data, *args, **kwargs)
File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
result = await self._flow_mgr.async_configure(flow_id, data)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 271, in async_configure
result = await self._async_handle_step(
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
result: FlowResult = await getattr(flow, method)(user_input)
File "/config/custom_components/haier/config_flow.py", line 145, in async_step_entity_device_selector
return await self.async_step_entity_filter()
File "/config/custom_components/haier/config_flow.py", line 186, in async_step_entity_filter
spec_resp = await client.get_hardware_config(target_device['wifi_type'])
File "/config/custom_components/haier/haier.py", line 181, in get_hardware_config
raise HaierClientException('获取配置文件失败')
custom_components.haier.haier.HaierClientException: 获取配置文件失败
2023-07-21 23:54:51.973 ERROR (MainThread) [custom_components.haier.haier] 获取配置信息失败, wifi_type: 111c12002400081005010021800111000000e400000000000000000000000000, response: {"status": "1", "data": null, "total": 0}
2023-07-21 23:54:51.981 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
resp = await request_handler(request)
File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
result = await result
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 241, in post
return await super().post(request, flow_id)
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
result = await method(view, request, data, *args, **kwargs)
File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
result = await self._flow_mgr.async_configure(flow_id, data)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 271, in async_configure
result = await self._async_handle_step(
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
result: FlowResult = await getattr(flow, method)(user_input)
File "/config/custom_components/haier/config_flow.py", line 145, in async_step_entity_device_selector
return await self.async_step_entity_filter()
File "/config/custom_components/haier/config_flow.py", line 186, in async_step_entity_filter
spec_resp = await client.get_hardware_config(target_device['wifi_type'])
File "/config/custom_components/haier/haier.py", line 181, in get_hardware_config
raise HaierClientException('获取配置文件失败')
custom_components.haier.haier.HaierClientException: 获取配置文件失败

**Comment by banto6** [comment]
see https://github.com/banto6/haier/issues/34
