### ISSUE TITLE
热水器可以添加进来但是不能控制。

### ISSUE THREAD

**Issue by redhatme** [banto6/haier#185]
**问题描述**
热水器可以添加进来但是不能控制。比如开关状态，打开，立马自己就回弹，热水器也没有变化。

**环境信息:**
 - Homeassistant版本: [e.g. 2024.12.03]

**设备信息**

EC6005HD-BK7KAU1

设备ID可开启debug模式后可在`Device Info`部分的日志中找到。日志可在`配置 > 系统 > 日志 > 加载完整日志`中查看。

2024-12-15 18:58:01.575 WARNING (MainThread) [homeassistant.components.gree.coordinator] Device gree-9424b87561f5 is unresponsive for 0:24:59.978799 seconds
2024-12-15 18:58:03.233 DEBUG (MainThread) [custom_components.haier] token is valid
2024-12-15 18:58:03.867 DEBUG (MainThread) [custom_components.haier.core.client] Device Info: {'deviceId': '540853B19DB3', 'deviceName': '电热水器', 'deviceType': '06012099', 'online': False, 'permissions': [{'auth': {'control': True, 'set': True, 'view': True}, 'authType': 'owner'}], 'productCodeT': 'GA0T7K002', 'productNameT': 'EC6005HD-BK7KAU1', 'totalPermission': {'control': True, 'set': True, 'view': True}, 'wifiType': '201c120000118674061200418016850000000000000000000000000000000040'}
2024-12-15 18:58:03.873 INFO (MainThread) [custom_components.haier.core.client] Device 540853B19DB3 get digital model from cache successful
2024-12-15 18:58:03.874 DEBUG (MainThread) [custom_components.haier.core.client] Device Info: {'deviceId': '540853AEDD84', 'deviceName': '吸油烟机', 'deviceType': '0900101C', 'online': True, 'permissions': [{'auth': {'control': True, 'set': True, 'view': True}, 'authType': 'owner'}], 'productCodeT': 'FC53R0000', 'productNameT': 'CXW-358-CDY5UD', 'totalPermission': {'control': True, 'set': True, 'view': True}, 'wifiType': '201c10c714120210090156455aae7e00000085bc18799800305f7406c1863e40'}
2024-12-15 18:58:03.882 INFO (MainThread) [custom_components.haier.core.client] Device 540853AEDD84 get digital model from cache successful
2024-12-15 18:58:03.884 DEBUG (MainThread) [custom_components.haier] 共获取到2个设备
2024-12-15 18:58:04.047 DEBUG (MainThread) [custom_components.haier.core.client] WSSGateway: wss://wssgw.haier.net:56792
2024-12-15 18:58:04.050 INFO (MainThread) [custom_components.haier.core.client] url: wss://wssgw.haier.net:56792/userag?token=24b9252b8bc54a3d893978a80e32daca&agClientId=24b9252b8bc54a3d893978a80e32daca
2024-12-15 18:58:04.212 DEBUG (MainThread) [custom_components.haier.core.client] Sending heartbeat
2024-12-15 18:58:04.241 DEBUG (MainThread) [custom_components.haier.core.client] Received websocket data: {"agClientId": "24b9252b8bc54a3d893978a80e32daca", "topic": "HeartBeatAck", "content": {"sn": "b7902adf245b6c864beaf48942a130da"}}
2024-12-15 18:58:07.901 DEBUG (MainThread) [custom_components.haier.core.client] Sending heartbeat
2024-12-15 18:58:07.923 DEBUG (MainThread) [custom_components.haier.core.client] Received websocket data: {"agClientId": "24b9252b8bc54a3d893978a80e32daca", "topic": "HeartBeatAck", "content": {"sn": "e7366813684cd5bd68a5b0fd1b9d4442"}}
2024-12-15 18:58:07.924 INFO (MainThread) [custom_components.haier.core.client] listen device stopped.
2024-12-15 18:58:09.027 DEBUG (MainThread) [custom_components.haier.core.client] Received websocket data: {"agClientId": "24b9252b8bc54a3d893978a80e32daca", "topic": "BatchCmdResp", "content": {"errNo": 0, "sn": "4776da0904a49d88b5bde2d3a3663b38"}}
2024-12-15 18:58:09.052 DEBUG (MainThread) [custom_components.haier.core.client] Received websocket data: {"agClientId": "24b9252b8bc54a3d893978a80e32daca", "topic": "BatchCmdResult", "content": {"trace": "a5cb526ed15d15aaac4f9f1de4fe43cb", "data": "{\"cmdSn\":\"4776da0904a49d88b5bde2d3a3663b38\",\"utraceId\":\"a5cb526ed15d15aaac4f9f1de4fe43cb\",\"batchResult\":false,\"batchResultInfo\":\"\",\"detailInfo\":[{\"oid\":0,\"cmdSubSn\":\"a5cb526ed15d15aaac4f9f1de4fe43cb@4776da0904a49d88b5bde2d3a3663b38:_:000\",\"outResultDetail\":\"{\\\"code\\\":\\\"03002\\\",\\\"info\\\":\\\"\u8bbe\u5907\u4e0d\u5728\u7ebf\\\",\\\"success\\\":false}\",\"execStep\":1,\"execResult\":false,\"execResultInfo\":\"\u8bbe\u5907\u79bb\u7ebf\",\"execResultCode\":\"S03002\",\"resultTime\":1734317889028,\"deviceId\":\"540853B19DB3\",\"patchType\":\"0\",\"pid\":\"PID_GA0T7K002\",\"productCodeT\":\"GA0T7K002\"}]}"}}
2024-12-15 18:58:09.257 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=16 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=16, family=2, type=2, proto=0, laddr=('0.0.0.0', 41559)>
2024-12-15 18:58:09.563 DEBUG (MainThread) [custom_components.haier.core.client] Received websocket data: {"agClientId": "24b9252b8bc54a3d893978a80e32daca", "topic": "BatchCmdResp", "content": {"errNo": 0, "sn": "7a4a0e29d0263848658354c81f22f5cb"}}
2024-12-15 18:58:09.590 DEBUG (MainThread) [custom_components.haier.core.client] Received websocket data: {"agClientId": "24b9252b8bc54a3d893978a80e32daca", "topic": "BatchCmdResult", "content": {"trace": "1497f800844c84b66711e2c160289af5", "data": "{\"cmdSn\":\"7a4a0e29d0263848658354c81f22f5cb\",\"utraceId\":\"1497f800844c84b66711e2c160289af5\",\"batchResult\":false,\"batchResultInfo\":\"\",\"detailInfo\":[{\"oid\":0,\"cmdSubSn\":\"1497f800844c84b66711e2c160289af5@7a4a0e29d0263848658354c81f22f5cb:_:000\",\"outResultDetail\":\"{\\\"code\\\":\\\"03002\\\",\\\"info\\\":\\\"\u8bbe\u5907\u4e0d\u5728\u7ebf\\\",\\\"success\\\":false}\",\"execStep\":1,\"execResult\":false,\"execResultInfo\":\"\u8bbe\u5907\u79bb\u7ebf\",\"execResultCode\":\"S03002\",\"resultTime\":1734317889565,\"deviceId\":\"540853B19DB3\",\"patchType\":\"0\",\"pid\":\"PID_GA0T7K002\",\"productCodeT\":\"GA0T7K002\"}]}"}}
2024-12-15 18:58:10.092 DEBUG (MainThread) [custom_components.haier.core.client] Received websocket data: {"agClientId": "24b9252b8bc54a3d893978a80e32daca", "topic": "BatchCmdResp", "content": {"errNo": 0, "sn": "fcb4af6373a7ce2e7b24b294cddd35ea"}}
2024-12-15 18:58:10.117 DEBUG (MainThread) [custom_components.haier.core.client] Received websocket data: {"agClientId": "24b9252b8bc54a3d893978a80e32daca", "topic": "BatchCmdResult", "content": {"trace": "c087b88a6c2ab5261678c3d49151fed2", "data": "{\"cmdSn\":\"fcb4af6373a7ce2e7b24b294cddd35ea\",\"utraceId\":\"c087b88a6c2ab5261678c3d49151fed2\",\"batchResult\":false,\"batchResultInfo\":\"\",\"detailInfo\":[{\"oid\":0,\"cmdSubSn\":\"c087b88a6c2ab5261678c3d49151fed2@fcb4af6373a7ce2e7b24b294cddd35ea:_:000\",\"outResultDetail\":\"{\\\"code\\\":\\\"03002\\\",\\\"info\\\":\\\"\u8bbe\u5907\u4e0d\u5728\u7ebf\\\",\\\"success\\\":false}\",\"execStep\":1,\"execResult\":false,\"execResultInfo\":\"\u8bbe\u5907\u79bb\u7ebf\",\"execResultCode\":\"S03002\",\"resultTime\":1734317890093,\"deviceId\":\"540853B19DB3\",\"patchType\":\"0\",\"pid\":\"PID_GA0T7K002\",\"productCodeT\":\"GA0T7K002\"}]}"}}
2024-12-15 18:58:10.676 DEBUG (MainThread) [custom_components.haier.core.client] Received websocket data: {"agClientId": "24b9252b8bc54a3d893978a80e32daca", "topic": "BatchCmdResp", "content": {"errNo": 0, "sn": "9a17bc3916853865c9bea894386787f9"}}
2024-12-15 18:58:10.702 DEBUG (MainThread) [custom_components.haier.core.client] Received websocket data: {"agClientId": "24b9252b8bc54a3d893978a80e32daca", "topic": "BatchCmdResult", "content": {"trace": "d966f1acf7091ca3d9e3cd552c638404", "data": "{\"cmdSn\":\"9a17bc3916853865c9bea894386787f9\",\"utraceId\":\"d966f1acf7091ca3d9e3cd552c638404\",\"batchResult\":false,\"batchResultInfo\":\"\",\"detailInfo\":[{\"oid\":0,\"cmdSubSn\":\"d966f1acf7091ca3d9e3cd552c638404@9a17bc3916853865c9bea894386787f9:_:000\",\"outResultDetail\":\"{\\\"code\\\":\\\"03002\\\",\\\"info\\\":\\\"\u8bbe\u5907\u4e0d\u5728\u7ebf\\\",\\\"success\\\":false}\",\"execStep\":1,\"execResult\":false,\"execResultInfo\":\"\u8bbe\u5907\u79bb\u7ebf\",\"execResultCode\":\"S03002\",\"resultTime\":1734317890678,\"deviceId\":\"540853B19DB3\",\"patchType\":\"0\",\"pid\":\"PID_GA0T7K002\",\"productCodeT\":\"GA0T7K002\"}]}"}}
2024-12-15 18:58:17.933 DEBUG (MainThread) [custom_components.haier.core.client] process_id not match, skip...
2024-12-15 18:58:17.934 INFO (MainThread) [custom_components.haier.core.client] listen device stopped.

**错误日志**
此错误来自自定义集成。

日志记录器: custom_components.haier.core.client 来源: custom_components/haier/core/client.py:170 集成: Haier (文档, 问题) 首次出现: 10:27:52 (2 次总计出现) 上次记录: 10:27:52
* Device 540853B19DB3 load cache digital model exception
* Device 540853AEDD84 load cache digital model exception
Traceback (most recent call last):
  File "/config/custom_components/haier/core/client.py", line 170, in get_digital_model_from_cache
    cache = await store.async_load()
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 290, in async_load
    result = await self._async_load()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 310, in _async_load
    return await self._async_load_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 413, in _async_load_data
    stored = await self._async_migrate_func(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        data["version"], data["minor_version"], data["data"]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 566, in _async_migrate_func
    raise NotImplementedError
NotImplementedError

**Comment by banto6** [comment]
设备是离线状态，看看APP能不能控制

**Comment by redhatme** [comment]
app可以控制。油烟机也可以控制。热水器还不行。

**Comment by banto6** [comment]
重新用master代码试试， 还不行的话就先点几下热水器的实体再提供一下日志
