### ISSUE TITLE
热水器在筛选中能看到，但是无生成任何实体

### ISSUE THREAD

**Issue by diy97** [banto6/haier#19]
报错：Unknown error occurred

日志：
Logger: aiohttp.server
Source: custom_components/haier/haier.py:181
Integration: Haier ([documentation](https://github.com/banto6/haier), [issues](https://github.com/banto6/haier/issues))
First occurred: 16:03:00 (1 occurrences)
Last logged: 16:03:00

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 241, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 271, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/haier/config_flow.py", line 145, in async_step_entity_device_selector
    return await self.async_step_entity_filter()
  File "/config/custom_components/haier/config_flow.py", line 186, in async_step_entity_filter
    spec_resp = await client.get_hardware_config(target_device['wifi_type'])
  File "/config/custom_components/haier/haier.py", line 181, in get_hardware_config
    raise HaierClientException('获取配置文件失败')
custom_components.haier.haier.HaierClientException: 获取配置文件失败

Logger: custom_components.haier.haier
Source: custom_components/haier/haier.py:179
Integration: Haier ([documentation](https://github.com/banto6/haier), [issues](https://github.com/banto6/haier/issues))
First occurred: 15:57:17 (3 occurrences)
Last logged: 16:03:00

获取配置信息失败, wifi_type: 111c120024000810181300418002484300000200000000000000000000000000, response: {"status": "1", "data": null, "total": 0}

Logger: custom_components.haier
Source: custom_components/haier/haier.py:181
Integration: Haier ([documentation](https://github.com/banto6/haier), [issues](https://github.com/banto6/haier/issues))
First occurred: 15:57:17 (2 occurrences)
Last logged: 15:57:47

设备[18A7F132FC40]初始化失败
Traceback (most recent call last):
  File "/config/custom_components/haier/__init__.py", line 43, in async_setup_entry
    specs = await client.get_hardware_config(device.wifi_type)
  File "/config/custom_components/haier/haier.py", line 181, in get_hardware_config
    raise HaierClientException('获取配置文件失败')
custom_components.haier.haier.HaierClientException: 获取配置文件失败

**Comment by diy97** [comment]
2023-07-10 09:32:07.802 WARNING (SyncWorker_0) [homeassistant.util.yaml.loader] YAML file /config/configuration.yaml contains duplicate key "automation". Check lines 17 and 284
2023-07-10 09:32:08.095 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration haier which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-07-10 09:32:08.098 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-07-10 09:32:27.065 WARNING (MainThread) [homeassistant.setup] Setup of automation is taking over 10 seconds.
2023-07-10 09:32:27.113 WARNING (SyncWorker_3) [homeassistant.util.yaml.loader] YAML file /config/configuration.yaml contains duplicate key "automation". Check lines 17 and 284
2023-07-10 09:32:30.561 DEBUG (MainThread) [custom_components.haier] 共获取到2个设备
2023-07-10 09:32:30.562 DEBUG (MainThread) [custom_components.haier] 经过过滤后共获取到2个设备
2023-07-10 09:32:30.562 DEBUG (MainThread) [custom_components.haier] Device Info: {'_raw_data': {'deviceId': '18A7F132FC40', 'deviceName': '燃气热水器', 'deviceType': '18013001', 'online': True, 'permissions': [{'auth': {'control': True, 'set': True, 'view': True}, 'authType': 'owner'}], 'productCodeT': 'GD0REC003', 'productNameT': 'JSQ31-16WRS(12T)U1', 'totalPermission': {'control': True, 'set': True, 'view': True}, 'wifiType': '111c120024000810181300418002484300000200000000000000000000000000'}}
2023-07-10 09:32:31.795 ERROR (MainThread) [custom_components.haier.haier] 获取配置信息失败, wifi_type: 111c120024000810181300418002484300000200000000000000000000000000, response: {"status": "1", "data": null, "total": 0}
2023-07-10 09:32:31.802 ERROR (MainThread) [custom_components.haier] 设备[18A7F132FC40]初始化失败
Traceback (most recent call last):
File "/config/custom_components/haier/__init__.py", line 43, in async_setup_entry
specs = await client.get_hardware_config(device.wifi_type)
File "/config/custom_components/haier/haier.py", line 181, in get_hardware_config
raise HaierClientException('获取配置文件失败')
custom_components.haier.haier.HaierClientException: 获取配置文件失败
2023-07-10 09:32:31.806 DEBUG (MainThread) [custom_components.haier] Device Info: {'_raw_data': {'deviceId': '04E229C927AA', 'deviceName': '冰箱', 'deviceType': '0102800E', 'online': True, 'permissions': [{'auth': {'control': True, 'set': True, 'view': True}, 'authType': 'owner'}], 'productCodeT': 'BC10U0094', 'productNameT': 'BCD-405WDSKU1', 'totalPermission': {'control': True, 'set': True, 'view': True}, 'wifiType': '200861051c408504012800618006984a00000000000061800312570000000040'}}
2023-07-10 09:32:33.024 DEBUG (MainThread) [custom_components.haier.coordinator] 设备[04E229C927AA]已获取到最新状态数据: {"freezerTemperatureC": "-18", "envTemperature": "34", "refrigeratorDoorStatus": "false", "intelligenceMode": "true", "envHumidity": "65", "quickFreezingMode": "false", "humanSensingStatus": "true", "humanSensingResult": "0", "showStatus": "false", "freezerTargetTempLevel": "12", "refrigeratorTargetTempLevel": "6", "refrigeratorTemperatureC": "5"}
2023-07-10 09:32:33.024 DEBUG (MainThread) [custom_components.haier.coordinator] Finished fetching Haier Device [04E229C927AA] data in 0.309 seconds (success: True)

**Comment by banto6** [comment]
提示`获取配置文件失败`表示设备跟当前API不兼容，暂时没有解决方案，目前正在考虑更换API，可以关注一下后续更新。

**Comment by diy97** [comment]
好的，感谢大佬

**Comment by badboyman** [comment]
> 

遇到了同样问题，希望能早日更新解决，感谢感谢🙏

**Comment by CharlesJxx** [comment]
看看我这个是什么原因

2023-07-23 15:13:27.061 DEBUG (MainThread) [custom_components.haier.coordinator] Finished fetching Haier Device [AC82265DEAA0] data in 0.213 seconds (success: True)
2023-07-23 15:13:27.061 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up haier platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 353, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/haier/binary_sensor.py", line 19, in async_setup_entry
    await async_register_entity(
  File "/config/custom_components/haier/__init__.py", line 147, in async_register_entity
    if attribute.platform != platform:
       ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'platform'

**Comment by banto6** [comment]
> 看看我这个是什么原因
> 
> 2023-07-23 15:13:27.061 DEBUG (MainThread) [custom_components.haier.coordinator] Finished fetching Haier Device [AC82265DEAA0] data in 0.213 seconds (success: True) 2023-07-23 15:13:27.061 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up haier platform for binary_sensor Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 353, in _async_setup_platform await asyncio.shield(task) File "/config/custom_components/haier/binary_sensor.py", line 19, in async_setup_entry await async_register_entity( File "/config/custom_components/haier/**init**.py", line 147, in async_register_entity if attribute.platform != platform: ^^^^^^^^^^^^^^^^^^ AttributeError: 'NoneType' object has no attribute 'platform'

新开一个issue反馈一下设备，这里回复会打扰到别人。
