### ISSUE TITLE
提交后报错，Error setting up entry haier for haier Traceback (most recent call last）

### ISSUE THREAD

**Issue by dingzhenying** [banto6/haier#2]
![image](https://github.com/banto6/haier/assets/30385060/8eab9d09-e987-494d-883b-22656b5367e9)
报错信息：
Error setting up entry haier for haier
Traceback (most recent call last):
  File "/Users/dingzhenying/.homeassistant/lib/python3.11/site-packages/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dingzhenying/.homeassistant/custom_components/haier/__init__.py", line 29, in async_setup_entry
    coordinator = await new_device_coordinator(hass, client, device)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dingzhenying/.homeassistant/custom_components/haier/__init__.py", line 53, in new_device_coordinator
    device['config'] = await client.get_hardware_config(device['wifiType'])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dingzhenying/.homeassistant/custom_components/haier/haier.py", line 109, in get_hardware_config
    async with http_client.get(url=content['data']['url']) as config_resp:
                                   ~~~~~~~~~~~~~~~^^^^^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by banto6** [comment]
看样子是设备的配置文件拉取失败了，我现在加上了日志，您可以拉取一下最新代码看看日志输出呢

**Comment by dingzhenying** [comment]
![image](https://github.com/banto6/haier/assets/30385060/48f03fc3-5256-4dd5-bcf3-84325ded9c18)
更新后，设备依旧无法加载，以上为日志报错信息，设备为海尔中央空调

**Comment by dingzhenying** [comment]
![image](https://github.com/banto6/haier/assets/30385060/cfcdd5bf-7615-40c1-b5a2-26292dde0a34)

**Comment by banto6** [comment]
是WIFI设备吗？

**Comment by dingzhenying** [comment]
是的，通过wifi接入的

**Comment by banto6** [comment]
在海尔智家APP中可以正常控制吗？是新设备还是老设备呢？看日志接口确实没有返回配置文件，有可能是本项目使用的API跟海尔智家APP使用的API不一致导致的。

**Comment by dingzhenying** [comment]
是海尔的中央空调，智家app中是能正常搜索和控制的，但在插件中设备无法被加载成功。以下为日志信息：

2023-07-04 09:20:54.131 ERROR (MainThread) [custom_components.haier] 设备[04E229535562_1-1]初始化失败
Traceback (most recent call last):
File "/Users/dingzhenying/.homeassistant/custom_components/haier/__init__.py", line 34, in async_setup_entry
coordinator = await new_device_coordinator(hass, client, device)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/dingzhenying/.homeassistant/custom_components/haier/__init__.py", line 78, in new_device_coordinator
device['config'] = await client.get_hardware_config(device['wifiType'])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/dingzhenying/.homeassistant/custom_components/haier/haier.py", line 142, in get_hardware_config
if 'data' not in content or 'url' not in content['data']:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2023-07-04 09:20:54.135 DEBUG (MainThread) [custom_components.haier] Device Info: {"deviceId": "04E229535562_1-2", "deviceName": "\u7a7a\u8c03", "deviceType": "0D082001", "online": true, "permissions": [{"auth": {"control": true, "set": true, "view": true}, "authType": "owner"}, {"auth": {"control": true, "set": false, "view": true}, "authType": "home"}], "productCodeT": "AA9E9005A", "productNameT": "RFTSAD71MXS-V1", "totalPermission": {"control": true, "set": true, "view": true}, "wifiType": "01c12002400081034080000000100000"}
2023-07-04 09:20:59.476 ERROR (MainThread) [custom_components.haier] 设备[04E229535562_1-2]初始化失败
Traceback (most recent call last):
File "/Users/dingzhenying/.homeassistant/custom_components/haier/__init__.py", line 34, in async_setup_entry
coordinator = await new_device_coordinator(hass, client, device)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/dingzhenying/.homeassistant/custom_components/haier/__init__.py", line 78, in new_device_coordinator
device['config'] = await client.get_hardware_config(device['wifiType'])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/dingzhenying/.homeassistant/custom_components/haier/haier.py", line 142, in get_hardware_config
if 'data' not in content or 'url' not in content['data']:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2023-07-04 09:20:59.478 DEBUG (MainThread) [custom_components.haier] Device Info: {"deviceId": "04E229535562_1-3", "deviceName": "\u7a7a\u8c03", "deviceType": "0D082001", "online": true, "permissions": [{"auth": {"control": true, "set": true, "view": true}, "authType": "owner"}, {"auth": {"control": true, "set": false, "view": true}, "authType": "home"}], "productCodeT": "AA9E9005A", "productNameT": "RFTSAD71MXS-V1", "totalPermission": {"control": true, "set": true, "view": true}, "wifiType": "01c12002400081034080000000100000"}
2023-07-04 09:20:59.879 ERROR (MainThread) [custom_components.haier] 设备[04E229535562_1-3]初始化失败
Traceback (most recent call last):
File "/Users/dingzhenying/.homeassistant/custom_components/haier/__init__.py", line 34, in async_setup_entry
coordinator = await new_device_coordinator(hass, client, device)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/dingzhenying/.homeassistant/custom_components/haier/__init__.py", line 78, in new_device_coordinator
device['config'] = await client.get_hardware_config(device['wifiType'])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/dingzhenying/.homeassistant/custom_components/haier/haier.py", line 142, in get_hardware_config
if 'data' not in content or 'url' not in content['data']:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2023-07-04 09:20:59.880 DEBUG (MainThread) [custom_components.haier] Device Info: {"deviceId": "04E229535562_1-4", "deviceName": "\u7a7a\u8c03", "deviceType": "0D082001", "online": true, "permissions": [{"auth": {"control": true, "set": true, "view": true}, "authType": "owner"}, {"auth": {"control": true, "set": false, "view": true}, "authType": "home"}], "productCodeT": "AA9E9005A", "productNameT": "RFTSAD71MXS-V1", "totalPermission": {"control": true, "set": true, "view": true}, "wifiType": "01c12002400081034080000000100000"}
2023-07-04 09:21:00.510 ERROR (MainThread) [custom_components.haier] 设备[04E229535562_1-4]初始化失败
Traceback (most recent call last):
File "/Users/dingzhenying/.homeassistant/custom_components/haier/__init__.py", line 34, in async_setup_entry
coordinator = await new_device_coordinator(hass, client, device)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/dingzhenying/.homeassistant/custom_components/haier/__init__.py", line 78, in new_device_coordinator
device['config'] = await client.get_hardware_config(device['wifiType'])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/dingzhenying/.homeassistant/custom_components/haier/haier.py", line 142, in get_hardware_config
if 'data' not in content or 'url' not in content['data']:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
