### ISSUE TITLE
卡萨帝冰箱识别不了

### ISSUE THREAD

**Issue by chen3286822** [banto6/haier#21]
在添加设备里能找到冰箱，设备添加不进去：

此错误来自自定义集成。

Logger: custom_components.haier
Source: custom_components/haier/haier.py:181
Integration: Haier (documentation, issues)
First occurred: 11:04:22 (2 occurrences)
Last logged: 13:54:38

设备[DC330DE0A63D]初始化失败
Traceback (most recent call last):
  File "/config/custom_components/haier/__init__.py", line 44, in async_setup_entry
    specs = await client.get_hardware_config(device.wifi_type)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/haier.py", line 181, in get_hardware_config
    raise HaierClientException('获取配置文件失败')
custom_components.haier.haier.HaierClientException: 获取配置文件失败

**Comment by banto6** [comment]
提示`获取配置文件失败`表示设备跟当前API不兼容，暂时没有解决方案，目前正在考虑更换API，可以关注一下后续更新。

**Comment by chen3286822** [comment]
好的，后面我关注一下
