### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by astangcong** [banto6/haier#24]
卡萨帝空调无法接入，只显示有设备和几个好像是音响才有的实体（音量、ota这些），别的都不行
 - Homeassistant版本: [e.g. 2023.7.2]
deviceType:02012036
productCodeT:AABMZD000
productNameT:CAS35GCA(81)U1室内机总成
wifiType:2008610800820324021200118006915900000000000000000000000000000040
**错误日志**
2023-07-15 00:57:55.728 ERROR (MainThread) [custom_components.haier.core.device] 获取attributes失败
Traceback (most recent call last):
  File "/config/custom_components/haier/core/device.py", line 70, in async_init
    self._attributes.append(parser.parse_attribute(item))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/core/attribute.py", line 68, in parse_attribute
    return self._parse_as_sensor(attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/core/attribute.py", line 102, in _parse_as_sensor
    if 'unit' in attribute['variants']:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2023-07-15 00:57:56.894 ERROR (MainThread) [custom_components.haier.core.device] 获取attributes失败
Traceback (most recent call last):
  File "/config/custom_components/haier/core/device.py", line 70, in async_init
    self._attributes.append(parser.parse_attribute(item))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/core/attribute.py", line 68, in parse_attribute
    return self._parse_as_sensor(attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/core/attribute.py", line 102, in _parse_as_sensor
    if 'unit' in attribute['variants']:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2023-07-15 00:58:00.658 WARNING (MainThread) [homeassistant.components.kodi.media_player] Unable to connect to Kodi via websocket
2023-07-15 01:11:36.420 ERROR (MainThread) [custom_components.haier.core.device] 获取attributes失败
Traceback (most recent call last):
  File "/config/custom_components/haier/core/device.py", line 70, in async_init
    self._attributes.append(parser.parse_attribute(item))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/core/attribute.py", line 68, in parse_attribute
    return self._parse_as_sensor(attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/core/attribute.py", line 102, in _parse_as_sensor
    if 'unit' in attribute['variants']:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2023-07-15 01:11:36.872 ERROR (MainThread) [custom_components.haier.core.device] 获取attributes失败
Traceback (most recent call last):
  File "/config/custom_components/haier/core/device.py", line 70, in async_init
    self._attributes.append(parser.parse_attribute(item))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/core/attribute.py", line 68, in parse_attribute
    return self._parse_as_sensor(attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/core/attribute.py", line 102, in _parse_as_sensor
    if 'unit' in attribute['variants']:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2023-07-15 01:12:06.115 DEBUG (MainThread) [custom_components.haier] reload.....
2023-07-15 01:12:07.089 ERROR (MainThread) [custom_components.haier.core.device] 获取attributes失败
Traceback (most recent call last):
  File "/config/custom_components/haier/core/device.py", line 70, in async_init
    self._attributes.append(parser.parse_attribute(item))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/core/attribute.py", line 68, in parse_attribute
    return self._parse_as_sensor(attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/core/attribute.py", line 102, in _parse_as_sensor
    if 'unit' in attribute['variants']:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2023-07-15 01:12:07.563 ERROR (MainThread) [custom_components.haier.core.device] 获取attributes失败
Traceback (most recent call last):
  File "/config/custom_components/haier/core/device.py", line 70, in async_init
    self._attributes.append(parser.parse_attribute(item))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/core/attribute.py", line 68, in parse_attribute
    return self._parse_as_sensor(attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/core/attribute.py", line 102, in _parse_as_sensor
    if 'unit' in attribute['variants']:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2023-07-15 01:12:07.564 DEBUG (MainThread) [custom_components.haier] 共获取到2个设备
2023-07-15 01:12:07.736 DEBUG (MainThread) [custom_components.haier.coordinator] 设备[04E2290EXXXX]已获取到最新状态数据: {"windSensingStatus": "false", "silentSleepStatus": "false", "humidificationStatus": "false", "intelligenceStatus": "false", "location": "", "messageVersion": "", "pm2p5ExceedRemind": "0", "electricHeatingStatus": "false", "ch2oValue": "0", "rapidMode": "false", "voiceSignStatus": "false", "specialMode": "0", "energySavePeriod": "15", "10degreeHeatingStatus": "false", "time": "00:00:00", "ch2oCleaningStatus": "false", "humanSensingStatus": "0", "outdoorPM2p5Value": "0", "scheduleVersion": "", "acType": "0", "playControl": "0", "lightStatus": "false", "dialect": "0", "totalCleaningTime": "0", "updateStatus": "false", "authVersion": "0", "errCode": "0", "totalElectricityUsed": "0", "tempUnit": "1", "sensingResult": "0", "currentMediaName": "", "lockStatus": "false", "clientId": "", "playProgress": "0", "selfCleaningStatus": "false", "runningMode": "1", "airQuality": "0", "playTime": "0", "operationModeHK": "0", "hardVersion": "", "voiceStatus": "false", "operationMode": "1", "playStatus": "false", "co2Value": "0", "targetTemperature": "27.00", "vocValue": "0", "energySavingStatus": "false", "localFilterChangeFlag": "false", "freshAirStatus": "false", "onOffStatus": "false", "windDirectionVertical": "5", "halfDegreeSettingStatus": "false", "date": "00:00:00", "echoStatus": "false", "freshWindSpeed": "0", "outdoorTemperature": "29.00", "uniqueId": "", "pm2p5Level": "0", "voiceRecogMode": "0", "token": "", "currentSongFavourited": "false", "voiceprintRecogStatus": "false", "humidityCtrlStatus": "false", "vboxId?": "", "co2ExceedRemind": "0", "indoorPM2p5Value": "0", "muteStatus": "false", "pmvStatus": "false", "healthMode": "false", "ErrAckFlag": "false", "pm2p5CleaningStatus": "false", "targetHumidity": "30", "softVersion": "", "indoorTemperature": "29.50", "windSpeed": "5", "heatAccumulationStatus": "false", "opSrc": "3", "playMode": "1", "volume": "100", "selfCleaning56Status": "false", "screenDisplayStatus": "true", "otaControl": "0", "windDirectionHorizontal": "5", "indoorHumidity": "64"}
2023-07-15 01:12:07.736 DEBUG (MainThread) [custom_components.haier.coordinator] Finished fetching Haier Device [04E2290EXXXX] data in 0.171 seconds (success: True)
2023-07-15 01:12:07.742 DEBUG (MainThread) [custom_components.haier.coordinator] 设备[04E2290EXXXX]已获取到最新状态数据: {"windSensingStatus": "false", "silentSleepStatus": "false", "humidificationStatus": "false", "intelligenceStatus": "false", "location": "", "messageVersion": "", "pm2p5ExceedRemind": "0", "electricHeatingStatus": "false", "ch2oValue": "0", "rapidMode": "false", "voiceSignStatus": "false", "specialMode": "0", "energySavePeriod": "15", "10degreeHeatingStatus": "false", "time": "00:00:00", "ch2oCleaningStatus": "false", "humanSensingStatus": "0", "outdoorPM2p5Value": "0", "scheduleVersion": "", "acType": "0", "playControl": "0", "lightStatus": "false", "dialect": "0", "totalCleaningTime": "0", "updateStatus": "false", "authVersion": "0", "errCode": "0", "totalElectricityUsed": "0", "tempUnit": "1", "sensingResult": "0", "currentMediaName": "", "lockStatus": "false", "clientId": "", "playProgress": "0", "selfCleaningStatus": "false", "runningMode": "1", "airQuality": "0", "playTime": "0", "operationModeHK": "0", "hardVersion": "", "voiceStatus": "false", "operationMode": "1", "playStatus": "false", "co2Value": "0", "targetTemperature": "27.00", "vocValue": "0", "energySavingStatus": "false", "localFilterChangeFlag": "false", "freshAirStatus": "false", "onOffStatus": "false", "windDirectionVertical": "5", "halfDegreeSettingStatus": "false", "date": "00:00:00", "echoStatus": "false", "freshWindSpeed": "0", "outdoorTemperature": "29.00", "uniqueId": "", "pm2p5Level": "0", "voiceRecogMode": "0", "token": "", "currentSongFavourited": "false", "voiceprintRecogStatus": "false", "humidityCtrlStatus": "false", "vboxId?": "", "co2ExceedRemind": "0", "indoorPM2p5Value": "0", "muteStatus": "false", "pmvStatus": "false", "healthMode": "false", "ErrAckFlag": "false", "pm2p5CleaningStatus": "false", "targetHumidity": "30", "softVersion": "", "indoorTemperature": "29.50", "windSpeed": "5", "heatAccumulationStatus": "false", "opSrc": "3", "playMode": "1", "volume": "100", "selfCleaning56Status": "false", "screenDisplayStatus": "true", "otaControl": "0", "windDirectionHorizontal": "5", "indoorHumidity": "64"}
2023-07-15 01:12:07.742 DEBUG (MainThread) [custom_components.haier.coordinator] Finished fetching Haier Device [04E2290EXXXX] data in 0.177 seconds (success: True)
2023-07-15 01:12:07.744 DEBUG (MainThread) [custom_components.haier.coordinator] 设备[04E2290EXXXX]已获取到最新状态数据: {"windSensingStatus": "false", "silentSleepStatus": "false", "humidificationStatus": "false", "intelligenceStatus": "false", "location": "", "messageVersion": "", "pm2p5ExceedRemind": "0", "electricHeatingStatus": "false", "ch2oValue": "0", "rapidMode": "false", "voiceSignStatus": "false", "specialMode": "0", "energySavePeriod": "15", "10degreeHeatingStatus": "false", "time": "00:00:00", "ch2oCleaningStatus": "false", "humanSensingStatus": "0", "outdoorPM2p5Value": "0", "scheduleVersion": "", "acType": "0", "playControl": "0", "lightStatus": "false", "dialect": "0", "totalCleaningTime": "0", "updateStatus": "false", "authVersion": "0", "errCode": "0", "totalElectricityUsed": "0", "tempUnit": "1", "sensingResult": "0", "currentMediaName": "", "lockStatus": "false", "clientId": "", "playProgress": "0", "selfCleaningStatus": "false", "runningMode": "1", "airQuality": "0", "playTime": "0", "operationModeHK": "0", "hardVersion": "", "voiceStatus": "false", "operationMode": "1", "playStatus": "false", "co2Value": "0", "targetTemperature": "27.00", "vocValue": "0", "energySavingStatus": "false", "localFilterChangeFlag": "false", "freshAirStatus": "false", "onOffStatus": "false", "windDirectionVertical": "5", "halfDegreeSettingStatus": "false", "date": "00:00:00", "echoStatus": "false", "freshWindSpeed": "0", "outdoorTemperature": "29.00", "uniqueId": "", "pm2p5Level": "0", "voiceRecogMode": "0", "token": "", "currentSongFavourited": "false", "voiceprintRecogStatus": "false", "humidityCtrlStatus": "false", "vboxId?": "", "co2ExceedRemind": "0", "indoorPM2p5Value": "0", "muteStatus": "false", "pmvStatus": "false", "healthMode": "false", "ErrAckFlag": "false", "pm2p5CleaningStatus": "false", "targetHumidity": "30", "softVersion": "", "indoorTemperature": "29.50", "windSpeed": "5", "heatAccumulationStatus": "false", "opSrc": "3", "playMode": "1", "volume": "100", "selfCleaning56Status": "false", "screenDisplayStatus": "true", "otaControl": "0", "windDirectionHorizontal": "5", "indoorHumidity": "64"}
2023-07-15 01:12:07.744 DEBUG (MainThread) [custom_components.haier.coordinator] Finished fetching Haier Device [04E2290EXXXX] data in 0.177 seconds (success: True)
2023-07-15 01:12:07.745 DEBUG (MainThread) [custom_components.haier.coordinator] 设备[04E2290EXXXX]已获取到最新状态数据: {"windSensingStatus": "false", "silentSleepStatus": "false", "humidificationStatus": "false", "intelligenceStatus": "false", "location": "", "messageVersion": "", "pm2p5ExceedRemind": "0", "electricHeatingStatus": "false", "ch2oValue": "0", "rapidMode": "false", "voiceSignStatus": "false", "specialMode": "0", "energySavePeriod": "15", "10degreeHeatingStatus": "false", "time": "00:00:00", "ch2oCleaningStatus": "false", "humanSensingStatus": "0", "outdoorPM2p5Value": "0", "scheduleVersion": "", "acType": "0", "playControl": "0", "lightStatus": "false", "dialect": "0", "totalCleaningTime": "0", "updateStatus": "false", "authVersion": "0", "errCode": "0", "totalElectricityUsed": "0", "tempUnit": "1", "sensingResult": "0", "currentMediaName": "", "lockStatus": "false", "clientId": "", "playProgress": "0", "selfCleaningStatus": "false", "runningMode": "1", "airQuality": "0", "playTime": "0", "operationModeHK": "0", "hardVersion": "", "voiceStatus": "false", "operationMode": "1", "playStatus": "false", "co2Value": "0", "targetTemperature": "27.00", "vocValue": "0", "energySavingStatus": "false", "localFilterChangeFlag": "false", "freshAirStatus": "false", "onOffStatus": "false", "windDirectionVertical": "5", "halfDegreeSettingStatus": "false", "date": "00:00:00", "echoStatus": "false", "freshWindSpeed": "0", "outdoorTemperature": "29.00", "uniqueId": "", "pm2p5Level": "0", "voiceRecogMode": "0", "token": "", "currentSongFavourited": "false", "voiceprintRecogStatus": "false", "humidityCtrlStatus": "false", "vboxId?": "", "co2ExceedRemind": "0", "indoorPM2p5Value": "0", "muteStatus": "false", "pmvStatus": "false", "healthMode": "false", "ErrAckFlag": "false", "pm2p5CleaningStatus": "false", "targetHumidity": "30", "softVersion": "", "indoorTemperature": "29.50", "windSpeed": "5", "heatAccumulationStatus": "false", "opSrc": "3", "playMode": "1", "volume": "100", "selfCleaning56Status": "false", "screenDisplayStatus": "true", "otaControl": "0", "windDirectionHorizontal": "5", "indoorHumidity": "64"}
2023-07-15 01:12:07.745 DEBUG (MainThread) [custom_components.haier.coordinator] Finished fetching Haier Device [04E2290EXXXX] data in 0.180 seconds (success: True)

**Comment by banto6** [comment]
拉一下最新代码试试呢

**Comment by astangcong** [comment]
更新后已解决
