### ISSUE TITLE
[BUG] 空调climate实体无法控制

### ISSUE THREAD

**Issue by FaintGhost** [banto6/haier#25]
**问题描述**
最新master分支代码，climate实体可以正常显示，但是无法控制。经测试不管是`运行模式`还是`风速`都无法控制并且无法同步状态，只有`扫风模式`可以同步状态但是依然无法控制。手动使用遥控器开启空调之后，`运行模式`和`风速`均显示为空白，并且climate实体的状态显示为未知，其他单独表示空调状态的sensor实体可以正常显示空调状态。

**环境信息:**
 - Homeassistant版本: 2023.7.2

**设备信息**
```
deviceType: 0201201G
productCodeT: AAABNH001
productNameT: KFR-35GW/05SNA81U1套机
wifiType: 2008610800820324021200118007264200000000000000000000000000000040
```
```
deviceType: 0301200L
productCodeT: AB91T7012
productNameT: KFR-72L/RAC81U1室内机总成
wifiType: 2008610800820324031200118006114500000000000000000000000000000040
```
**错误日志**
加载全部日志之后暂无相关报错，控制climate实体的时候也没有产生call service失败错误。

**Comment by banto6** [comment]
给一份空调运行过程中的数据呢。开启debug后截取这部分数据 `设备[xxxxxxx]已获取到最新状态数据: `

**Comment by FaintGhost** [comment]
数据如下，可能一直开着有几万条这样的数据
```
2023-07-18 22:50:58.599 DEBUG (MainThread) [custom_components.haier.coordinator] 设备[18A7F146A350]已获取到最新状态数据: {"intelligenceStatus": "false", "humidificationStatus": "false", "silentSleepStatus": "false", "electricHeatingStatus": "false", "ch2oValue": "0", "rapidMode": "false", "energySavePeriod": "15", "specialMode": "0", "10degreeHeatingStatus": "false", "ch2oCleaningStatus": "false", "humanSensingStatus": "0", "outdoorPM2p5Value": "0", "acType": "0", "lightStatus": "false", "totalCleaningTime": "0", "errCode": "", "totalElectricityUsed": "0", "sensingResult": "0", "tempUnit": "1", "lockStatus": "false", "selfCleaningStatus": "false", "airQuality": "0", "operationModeHK": "0", "operationMode": "6", "co2Value": "0", "targetTemperature": "26.00", "vocValue": "0", "localFilterChangeFlag": "false", "energySavingStatus": "false", "freshAirStatus": "false", "windDirectionVertical": "8", "onOffStatus": "true", "halfDegreeSettingStatus": "false", "echoStatus": "false", "outdoorTemperature": "33.00", "pm2p5Level": "0", "indoorPM2p5Value": "0", "pmvStatus": "false", "muteStatus": "false", "healthMode": "false", "ErrAckFlag": "false", "pm2p5CleaningStatus": "false", "targetHumidity": "30", "indoorTemperature": "29.50", "windSpeed": "2", "heatAccumulationStatus": "false", "opSrc": "1", "screenDisplayStatus": "true", "windDirectionHorizontal": "7", "indoorHumidity": "0"}
2023-07-18 22:50:58.600 DEBUG (MainThread) [custom_components.haier.coordinator] Finished fetching Haier Device [18A7F146A350] data in 0.156 seconds (success: True)
```

**Comment by banto6** [comment]
再次用最新的代码试试呢  看看空调运行状态和参数能不能正确同步到HA上；能正常同步的话，在保持空调开机的情况下调整运行模式、温度等参数试试

**Comment by astangcong** [comment]
空调climate开关 不能用，只能用单独的开关状态实体控制打开或者关闭

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/haier/climate.py:108
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 23:46:20 (2 occurrences)
Last logged: 23:46:31

[139846685231440] <HVACMode.OFF: 'off'>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 205, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1965, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2005, in _execute_service
    return await cast(
           ^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 848, in entity_service_call
    response_data = task.result()  # pop exception if have
                    ^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1192, in async_request_call
    return await coro
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 892, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 497, in async_set_hvac_mode
    await self.hass.async_add_executor_job(self.set_hvac_mode, hvac_mode)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/climate.py", line 108, in set_hvac_mode
    'operationMode': {
                     ^
KeyError: <HVACMode.OFF: 'off'>








2023-07-19 23:46:20.288 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139846685231440] <HVACMode.OFF: 'off'>
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 205, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1965, in async_call
response_data = await coro
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 2005, in _execute_service
return await cast(
^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
return await service.entity_service_call(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 848, in entity_service_call
response_data = task.result() # pop exception if have
^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1192, in async_request_call
return await coro
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 892, in _handle_entity_call
result = await task
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 497, in async_set_hvac_mode
await self.hass.async_add_executor_job(self.set_hvac_mode, hvac_mode)
File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/haier/climate.py", line 108, in set_hvac_mode
'operationMode': {
^
KeyError: <HVACMode.OFF: 'off'>
2023-07-19 23:46:31.135 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139846685231440] <HVACMode.OFF: 'off'>
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 205, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1965, in async_call
response_data = await coro
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 2005, in _execute_service
return await cast(
^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
return await service.entity_service_call(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 848, in entity_service_call
response_data = task.result() # pop exception if have
^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1192, in async_request_call
return await coro
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 892, in _handle_entity_call
result = await task
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 497, in async_set_hvac_mode
await self.hass.async_add_executor_job(self.set_hvac_mode, hvac_mode)
File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/haier/climate.py", line 108, in set_hvac_mode
'operationMode': {
^
KeyError: <HVACMode.OFF: 'off'>

**Comment by banto6** [comment]
加QQ群891954983测试吧，issue效率太低了
