### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by thfengxing** [banto6/haier#26]
**问题描述**
无法添加集成

**环境信息:**

Home Assistant 2023.1.7
前端版本： 20230110.0 - latest

添加集成时提示
无法加载配置向导: {"message":"Invalid handler specified"}

**Comment by thfengxing** [comment]
日志补充：

此错误来自自定义集成。

Logger: homeassistant.loader
Source: custom_components/haier/core/attribute.py:31
Integration: Haier (documentation, issues)
First occurred: 22:37:39 (1 occurrences)
Last logged: 22:37:39

Unexpected exception importing platform custom_components.haier.config_flow
Traceback (most recent call last):
  File "/Users/homeserver/Documents/HomeAssistant/lib/python3.9/site-packages/homeassistant/loader.py", line 744, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/Users/homeserver/Documents/HomeAssistant/lib/python3.9/site-packages/homeassistant/loader.py", line 761, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/homeserver/.homeassistant/custom_components/haier/__init__.py", line 12, in <module>
    from .coordinator import DeviceCoordinator
  File "/Users/homeserver/.homeassistant/custom_components/haier/coordinator.py", line 8, in <module>
    from .core.device import HaierDevice
  File "/Users/homeserver/.homeassistant/custom_components/haier/core/device.py", line 5, in <module>
    from .attribute import HaierAttribute, V1SpecAttributeParser
  File "/Users/homeserver/.homeassistant/custom_components/haier/core/attribute.py", line 9, in <module>
    class HaierAttribute:
  File "/Users/homeserver/.homeassistant/custom_components/haier/core/attribute.py", line 31, in HaierAttribute
    def unit(self) -> str | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by banto6** [comment]
我本地没有复现，调整了一下代码，重新拉一下代码试试

**Comment by thfengxing** [comment]
重新部署了python3.11和ha2023.7.2的core，已可以登陆
