### ISSUE TITLE
[BUG]获取配置文件失败

### ISSUE THREAD

**Issue by Wooo0** [banto6/haier#27]
**问题描述**
更新master之前在实体筛选中可以看到空调，更新之后实体筛选无法看到空调了
下面是更新之后的日志

**环境信息:**
 - Homeassistant版本: [e.g. 2023.6.2]

**设备信息**

```
'deviceType': '03001001',
'productCodeT': 'AB8Y74000'
'productNameT': 'KFR-72L/UDP21AU1室内机总成',
'wifiType': '00000000000000008080000000041410'
```

**错误日志**
2023-07-17 11:15:57.311 ERROR (MainThread) [custom_components.haier.core.client] 获取配置信息失败, wifi_type: 00000000000000008080000000041410, response: {"status": "1", "data": null, "total": 0}
2023-07-17 11:15:57.318 ERROR (MainThread) [custom_components.haier.core.device] 获取attributes失败
Traceback (most recent call last):
File "/config/custom_components/haier/core/device.py", line 68, in async_init
properties = (await self._client.get_hardware_config(self.wifi_type))['Property']
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/haier/core/client.py", line 153, in get_hardware_config
raise HaierClientException('获取配置文件失败')
custom_components.haier.core.client.HaierClientException: 获取配置文件失败
2023-07-17 11:15:57.329 ERROR (MainThread) [custom_components.haier] Device [2C37C52CB2D1] 未获取到可用attribute
2023-07-17 11:15:57.330 DEBUG (MainThread) [custom_components.haier] 共获取到0个设备
2023-07-17 11:16:28.546 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 581, in state
numerical_value = int(value)
^^^^^^^^^^

**Comment by banto6** [comment]
提示`获取配置文件失败`表示设备跟当前API不兼容，暂时没有解决方案，目前正在考虑更换API，可以关注一下后续更新。
