### ISSUE TITLE
海尔冰箱添加不了

### ISSUE THREAD

**Issue by wp861010** [banto6/haier#32]
此错误来自自定义集成。

Logger: custom_components.haier
Source: custom_components/haier/haier.py:181
Integration: Haier (documentation, issues)
First occurred: 10:32:44 (3 occurrences)
Last logged: 10:34:13

设备[DC330D4F52AE]初始化失败
Traceback (most recent call last):
  File "/config/custom_components/haier/__init__.py", line 43, in async_setup_entry
    specs = await client.get_hardware_config(device.wifi_type)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/haier.py", line 181, in get_hardware_config
    raise HaierClientException('获取配置文件失败')
custom_components.haier.haier.HaierClientException: 获取配置文件失败

**Comment by banto6** [comment]
see https://github.com/banto6/haier/issues/34
