### ISSUE TITLE
添加集成后不显示设备或实体

### ISSUE THREAD

**Issue by Cimsen** [banto6/haier#35]
**问题描述**
添加集成后不显示设备或实体

**环境信息:**
 Home Assistant 2023.6.2

**设备信息**
海尔空调KFR-35G/GAA23AU1
```
deviceType:
productCodeT:
productNameT:
wifiType:00000000000000008080000000041410
```

**错误日志**
2023-07-20 16:50:04.645 ERROR (MainThread) [custom_components.haier.core.client] 获取配置信息失败, wifi_type: 00000000000000008080000000041410, response: {"status": "1", "data": null, "total": 0}
2023-07-20 16:50:04.646 ERROR (MainThread) [custom_components.haier.core.device] 获取attributes失败
Traceback (most recent call last):
File "/config/custom_components/haier/core/device.py", line 69, in async_init
properties = (await self._client.get_hardware_config(self.wifi_type))['Property']
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/haier/core/client.py", line 153, in get_hardware_config
raise HaierClientException('获取配置文件失败')
custom_components.haier.core.client.HaierClientException: 获取配置文件失败
2023-07-20 16:50:05.134 ERROR (MainThread) [custom_components.haier.core.client] 获取配置信息失败, wifi_type: 111c120024000810010400618003474300000000000061800312430000000000, response: {"status": "1", "data": null, "total": 0}
2023-07-20 16:50:05.135 ERROR (MainThread) [custom_components.haier.core.device] 获取attributes失败
Traceback (most recent call last):
File "/config/custom_components/haier/core/device.py", line 69, in async_init
properties = (await self._client.get_hardware_config(self.wifi_type))['Property']
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/haier/core/client.py", line 153, in get_hardware_config
raise HaierClientException('获取配置文件失败')
custom_components.haier.core.client.HaierClientException: 获取配置文件失败
2023-07-20 16:50:05.651 ERROR (MainThread) [custom_components.haier.core.client] 获取配置信息失败, wifi_type: 00000000000000008080000000041410, response: {"status": "1", "data": null, "total": 0}
2023-07-20 16:50:05.652 ERROR (MainThread) [custom_components.haier.core.device] 获取attributes失败
Traceback (most recent call last):
File "/config/custom_components/haier/core/device.py", line 69, in async_init
properties = (await self._client.get_hardware_config(self.wifi_type))['Property']
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/haier/core/client.py", line 153, in get_hardware_config
raise HaierClientException('获取配置文件失败')
custom_components.haier.core.client.HaierClientException: 获取配置文件失败
2023-07-20 16:50:05.653 ERROR (MainThread) [custom_components.haier] Device [04FA83174579] 未获取到可用attribute
2023-07-20 16:50:05.653 ERROR (MainThread) [custom_components.haier] Device [DC330DCD3EC7] 未获取到可用attribute
2023-07-20 16:50:05.654 ERROR (MainThread) [custom_components.haier] Device [04FA83829220] 未获取到可用attribute
2023-07-20 16:50:05.654 DEBUG (MainThread) [custom_components.haier] 共获取到0个设备

**Comment by banto6** [comment]
https://github.com/banto6/haier/issues/34
