### ISSUE TITLE
[climate][bug]无法开关机

### ISSUE THREAD

**Issue by toutoumu** [banto6/haier#37]
**问题描述**
1. 使用Homekit(iPhone家庭APP)操作开机关机,无法开关机
2. 使用遥控开机,再使用HomeKit开关机,无法开关机, 但是可以制热制冷, 可以调温
3. 另外好像(iPhone家庭APP重) 摇摆 和 风扇模式 是反的

**环境信息:**
 - Homeassistant版本: [e.g. 2023.7.3]

**设备信息**
若是设备无法识别或控制错误则此项**必填**。

以下信息开启debug模式后可在`Device Info`部分的日志中找到。日志可在`配置 > 系统 > 日志 > 加载完整日志`中查看。
```
{'_raw_data': {'deviceId': 'A082225A9404', 'deviceName': '儿童房空调', 'deviceType': '02012036', 'online': True, 'permissions': [{'auth': {'control': True, 'set': False, 'view': True}, 'authType': 'home'}], 'productCodeT': 'AAABTT00M', 'productNameT': 'KFR-26G/KBB81U1室内机总成', 'totalPermission': {'control': True, 'set': False, 'view': True}, 'wifiType': '2008610800820324021200118006915900000000000000000000000000000040'}}
```

**错误日志**

此错误来自自定义集成。

Logger: homeassistant.core
Source: custom_components/haier/climate.py:108
Integration: Haier (documentation, issues)
First occurred: 22:42:27 (2 occurrences)
Last logged: 22:43:08

Error executing service: <ServiceCall climate.set_hvac_mode (c:01H5WEDVH6VCR6ZWJYYRYJGEZN): entity_id=['climate.a082225a9404_climate'], hvac_mode=off>
Error executing service: <ServiceCall climate.set_hvac_mode (c:01H5WEF3XWBF8CSWCEW03RYYXX): entity_id=['climate.a082225a9404_climate'], hvac_mode=off>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1983, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 2005, in _execute_service
    return await cast(
           ^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 848, in entity_service_call
    response_data = task.result()  # pop exception if have
                    ^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1192, in async_request_call
    return await coro
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 892, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 497, in async_set_hvac_mode
    await self.hass.async_add_executor_job(self.set_hvac_mode, hvac_mode)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/climate.py", line 108, in set_hvac_mode
    'operationMode': {
                     ^
KeyError: <HVACMode.OFF: 'off'>

**Comment by banto6** [comment]
使用最新代码试试呢

**Comment by toutoumu** [comment]
最新代码可以 关机, 但是开机还是不行
<img width="472" alt="image" src="https://github.com/banto6/haier/assets/8220920/becf1ea5-5cb3-4e1c-af61-ec8ea9f7f82a">

**Comment by banto6** [comment]
调整了一下逻辑 再试试呢

**Comment by toutoumu** [comment]
都可以了, 感谢大佬
