### ISSUE TITLE
climate卡片部分机型无法开机，风管机通过climate卡片无法正常开机，挂机正常

### ISSUE THREAD

**Issue by aihhkc** [banto6/haier#38]
**问题描述**
已使用最新代码climate卡片部分机型无法开机，我家有安装风管机与挂机，风管机通过climate卡片无法正常开机，
通过独立开关实体可以正常开关机

**环境信息:**
 - Homeassistant版本: 20230705.1 - latest

**设备信息**
若是设备无法识别或控制错误则此项**必填**。

deviceType:0201201G
productCodeT:AAABTB00E
productNameT:KFR-26G/KBB83U1室内机总成
wifiType:2008610800820324021200118007264200000000000000000000000000000040（挂机，climate卡片功能正常）

deviceType:0D012001
productCodeT:AA9KK9007
productNameT:KFRD-72NW/64DDA21Z
wifiType:201c1200240008100d12f71c4094f300000080e384181627a2904f4940b24240（风管机，climate卡片无法开机，通过独立开关实体开机之后操作正常关机正常）

deviceType:0D012001
productCodeT:AA9KK7007
productNameT:KFRD-36NW/61DBA21Z
wifiType:201c1200240008100d12f71c4094f300000080e384181627a2904f4940b24240（风管机，climate卡片无法开机，通过独立开关实体开机之后操作正常关机正常）

以下信息开启debug模式后可在`Device Info`部分的日志中找到。日志可在`配置 > 系统 > 日志 > 加载完整日志`中查看。
```
deviceType:0D012001
productCodeT:AA9KK7007
productNameT:KFRD-36NW/61DBA21Z
wifiType:201c1200240008100d12f71c4094f300000080e384181627a2904f4940b24240

deviceType:0D012001
productCodeT:AA9KK9007
productNameT:KFRD-72NW/64DDA21Z
wifiType:201c1200240008100d12f71c4094f300000080e384181627a2904f4940b24240

```

[**错误日志**]

设备[145790A56192]是挂机空调，climate卡片功能正常，正常开机
2023-07-23 10:44:20.561 DEBUG (MainThread) [custom_components.haier.coordinator] 设备[145790A56192]已获取到最新状态数据: {"intelligenceStatus": "false", "humidificationStatus": "false", "silentSleepStatus": "false", "electricHeatingStatus": "false", "ch2oValue": "0", "rapidMode": "false", "energySavePeriod": "15", "specialMode": "0", "10degreeHeatingStatus": "false", "ch2oCleaningStatus": "false", "humanSensingStatus": "0", "outdoorPM2p5Value": "0", "acType": "0", "lightStatus": "false", "totalCleaningTime": "0", "errCode": "", "totalElectricityUsed": "0", "sensingResult": "0", "tempUnit": "1", "lockStatus": "false", "selfCleaningStatus": "false", "airQuality": "0", "operationModeHK": "0", "operationMode": "6", "co2Value": "0", "targetTemperature": "26.00", "vocValue": "0", "localFilterChangeFlag": "false", "energySavingStatus": "false", "freshAirStatus": "false", "windDirectionVertical": "0", "onOffStatus": "false", "halfDegreeSettingStatus": "false", "echoStatus": "false", "outdoorTemperature": "33.00", "pm2p5Level": "0", "indoorPM2p5Value": "0", "pmvStatus": "false", "muteStatus": "false", "healthMode": "false", "ErrAckFlag": "false", "pm2p5CleaningStatus": "false", "targetHumidity": "30", "indoorTemperature": "31.50", "windSpeed": "2", "heatAccumulationStatus": "false", "opSrc": "3", "screenDisplayStatus": "true", "windDirectionHorizontal": "0", "indoorHumidity": "0"}
2023-07-23 10:44:20.561 DEBUG (MainThread) [custom_components.haier.coordinator] Finished fetching Haier Device [145790A56192] data in 0.280 seconds (success: True)
2023-07-23 10:44:34.541 DEBUG (MainThread) [custom_components.haier.coordinator] 设备[145790A56192]已获取到最新状态数据: {"intelligenceStatus": "false", "humidificationStatus": "false", "silentSleepStatus": "false", "electricHeatingStatus": "false", "ch2oValue": "0", "rapidMode": "false", "energySavePeriod": "15", "specialMode": "0", "10degreeHeatingStatus": "false", "ch2oCleaningStatus": "false", "humanSensingStatus": "0", "outdoorPM2p5Value": "0", "acType": "0", "lightStatus": "false", "totalCleaningTime": "0", "errCode": "", "totalElectricityUsed": "0", "sensingResult": "0", "tempUnit": "1", "lockStatus": "false", "selfCleaningStatus": "false", "airQuality": "0", "operationModeHK": "0", "operationMode": "6", "co2Value": "0", "targetTemperature": "26.00", "vocValue": "0", "localFilterChangeFlag": "false", "energySavingStatus": "false", "freshAirStatus": "false", "windDirectionVertical": "0", "onOffStatus": "true", "halfDegreeSettingStatus": "false", "echoStatus": "false", "outdoorTemperature": "33.00", "pm2p5Level": "0", "indoorPM2p5Value": "0", "pmvStatus": "false", "muteStatus": "false", "healthMode": "false", "ErrAckFlag": "false", "pm2p5CleaningStatus": "false", "targetHumidity": "30", "indoorTemperature": "31.50", "windSpeed": "2", "heatAccumulationStatus": "false", "opSrc": "3", "screenDisplayStatus": "true", "windDirectionHorizontal": "0", "indoorHumidity": "0"}

设备[3429EF28ADE4]是风管机空调，无法通过climate卡片开机，日志中没有看到对应的错误日志
2023-07-23 10:45:04.685 DEBUG (MainThread) [custom_components.haier.coordinator] 设备[3429EF28ADE4]已获取到最新状态数据: {"silentSleepStatus": "false", "co2Value": "0", "intelligenceStatus": "false", "humidificationStatus": "false", "targetTemperature": "27.00", "vocValue": "0", "localFilterChangeFlag": "false", "energySavingStatus": "false", "electricHeatingStatus": "false", "freshAirStatus": "false", "ch2oValue": "0", "rapidMode": "false", "onOffStatus": "false", "windDirectionVertical": "0", "halfDegreeSettingStatus": "false", "echoStatus": "false", "outdoorTemperature": "33.00", "specialMode": "0", "10degreeHeatingStatus": "false", "pm2p5Level": "0", "ch2oCleaningStatus": "false", "humanSensingStatus": "0", "outdoorPM2p5Value": "0", "indoorPM2p5Value": "0", "acType": "0", "muteStatus": "false", "pmvStatus": "false", "healthMode": "false", "ErrAckFlag": "false", "pm2p5CleaningStatus": "false", "lightStatus": "false", "targetHumidity": "30", "totalCleaningTime": "0", "errCode": "", "sensingResult": "0", "tempUnit": "1", "lockStatus": "false", "selfCleaningStatus": "false", "indoorTemperature": "30.00", "windSpeed": "2", "airQuality": "0", "opSrc": "3", "screenDisplayStatus": "true", "operationMode": "6", "windDirectionHorizontal": "0", "indoorHumidity": "0"}
2023-07-23 10:45:05.415 DEBUG (MainThread) [custom_components.haier.coordinator] 设备[3429EF28ADE4]已获取到最新状态数据: {"silentSleepStatus": "false", "co2Value": "0", "intelligenceStatus": "false", "humidificationStatus": "false", "targetTemperature": "27.00", "vocValue": "0", "localFilterChangeFlag": "false", "energySavingStatus": "false", "electricHeatingStatus": "false", "freshAirStatus": "false", "ch2oValue": "0", "rapidMode": "false", "onOffStatus": "false", "windDirectionVertical": "0", "halfDegreeSettingStatus": "false", "echoStatus": "false", "outdoorTemperature": "33.00", "specialMode": "0", "10degreeHeatingStatus": "false", "pm2p5Level": "0", "ch2oCleaningStatus": "false", "humanSensingStatus": "0", "outdoorPM2p5Value": "0", "indoorPM2p5Value": "0", "acType": "0", "muteStatus": "false", "pmvStatus": "false", "healthMode": "false", "ErrAckFlag": "false", "pm2p5CleaningStatus": "false", "lightStatus": "false", "targetHumidity": "30", "totalCleaningTime": "0", "errCode": "", "sensingResult": "0", "tempUnit": "1", "lockStatus": "false", "selfCleaningStatus": "false", "indoorTemperature": "30.00", "windSpeed": "2", "airQuality": "0", "opSrc": "3", "screenDisplayStatus": "true", "operationMode": "6", "windDirectionHorizontal": "0", "indoorHumidity": "0"}

日志中只有看到部分实体不可用的错误日志
2023-07-23 10:45:05.425 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 229, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 374, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in async_update_listeners
    update_callback()
  File "/config/custom_components/haier/entity.py", line 47, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 742, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 810, in _async_write_ha_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 748, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 572, in state
    raise ValueError(
ValueError: Sensor sensor.3429ef28ade4_pm2p5level provides state value '0', which is not in the list of options provided

**Comment by banto6** [comment]
独立开关实体是指`开关机状态`这个实体吗？

**Comment by aihhkc** [comment]
> 独立开关实体是指`开关机状态`这个实体吗？

对，通过开关状态实体，可以正常开关机

**Comment by banto6** [comment]
现在将运行模式从`关闭`切换到其他模式不能正常工作吗？如果先开机再切换模式能正常切换吗？

**Comment by aihhkc** [comment]
> 现在是将运行模式从`关闭`切换到其他模式不能正常工作吗？如果先开机再切换模式能正常切换吗？

是，只有 将运行模式从关闭切换到其他模式不能正常工作；
开机之后，功能都正常，切换模式，温度调节、风速调节、关机、操作都是正常的，

**Comment by banto6** [comment]
方便加群89195498吗？我发一份测试代码给你试试

**Comment by aihhkc** [comment]
> 方便加群89195498吗？我发一份测试代码给你试试

申请了

**Comment by banto6** [comment]
我没有看到申请呢，是QQ群额

**Comment by aihhkc** [comment]
> 89195498

加的是QQ群，群号错了?，加我QQ444515543

**Comment by banto6** [comment]
写漏了是  891954983

**Comment by aihhkc** [comment]
> 写漏了是 891954983

重新申请了
