### ISSUE TITLE
所有设备只有 sensor 和 binary sensor

### ISSUE THREAD

**Issue by tjaol** [banto6/haier#41]
**问题描述**
我有一台卡萨帝冰吧，和饮水机，还有几个开关，传感器，晾衣架，这些都正常导入了，但是实体只有  sensor 和 binary sensor，我的问题是 为什么没有 switch

**环境信息:**
 - Homeassistant版本: [e.g. 2023.6.2]

**设备信息**
若是设备无法识别或控制错误则此项**必填**。

以下信息开启debug模式后可在`Device Info`部分的日志中找到。日志可在`配置 > 系统 > 日志 > 加载完整日志`中查看。
```
deviceType:
productCodeT:
productNameT:
wifiType:
```

**错误日志**

**Comment by banto6** [comment]
补充一下设备信息

**Comment by tjaol** [comment]
Logger: homeassistant.components.switch
Source: custom_components/haier/core/device.py:39
Integration: Switch (documentation, issues)
First occurred: 5:02:17 AM (1 occurrences)
Last logged: 5:02:17 AM

Error while setting up haier platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 353, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/haier/switch.py", line 20, in async_setup_entry
    await async_register_entity(
  File "/config/custom_components/haier/__init__.py", line 162, in async_register_entity
    entities.append(setup(coordinator, device, attribute))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/switch.py", line 25, in <lambda>
    lambda coordinator, device, attribute: HaierSwitch(coordinator, device, attribute)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/switch.py", line 32, in __init__
    super().__init__(coordinator, device, attribute)
  File "/config/custom_components/haier/entity.py", line 32, in __init__
    model=device.product_name,
          ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/core/device.py", line 39, in product_name
    return self._raw_data['productNameT']
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'productNameT'

**Comment by tjaol** [comment]
Logger: homeassistant.components.number
Source: custom_components/haier/core/device.py:39
Integration: Number (documentation, issues)
First occurred: 5:02:17 AM (1 occurrences)
Last logged: 5:02:17 AM

Error while setting up haier platform for number
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 353, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/haier/number.py", line 18, in async_setup_entry
    await async_register_entity(
  File "/config/custom_components/haier/__init__.py", line 162, in async_register_entity
    entities.append(setup(coordinator, device, attribute))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/number.py", line 23, in <lambda>
    lambda coordinator, device, attribute: HaierNumber(coordinator, device, attribute)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/number.py", line 30, in __init__
    super().__init__(coordinator, device, attribute)
  File "/config/custom_components/haier/entity.py", line 32, in __init__
    model=device.product_name,
          ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/core/device.py", line 39, in product_name
    return self._raw_data['productNameT']
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'productNameT'

**Comment by tjaol** [comment]
请问能否 私下联系一下，我的微信 13301107610

**Comment by banto6** [comment]
使用最新代码试试，不行的话请按要求提供设备信息。
