### ISSUE TITLE
卡萨帝空调添加后无climate实体

### ISSUE THREAD

**Issue by Loyido** [banto6/haier#53]
**问题描述**
卡萨帝空调添加后无climate实体
设备名：CAP725WDA(A1)U1套机
制造商：海尔
<img width="326" alt="image" src="https://github.com/banto6/haier/assets/80599145/bb67ec64-6ce4-40ee-862d-1849f41a54ba">
<img width="321" alt="image" src="https://github.com/banto6/haier/assets/80599145/a2e4bbae-09ba-479b-9f1f-c72e7735ab13">
<img width="315" alt="image" src="https://github.com/banto6/haier/assets/80599145/4108d0a1-44ef-402b-a849-6cea65096700">

**环境信息:**
 - Homeassistant版本: 2023.8.3

**设备信息**
若是设备无法识别或控制错误则此项**必填**。

以下信息开启debug模式后可在`Device Info`部分的日志中找到。日志可在`配置 > 系统 > 日志 > 加载完整日志`中查看。
```
deviceType:
productCodeT:
productNameT:
wifiType:
```

上述信息在使用0.1.1版本的集成，开启调试模式后，重启HA，未获取到。
<img width="433" alt="image" src="https://github.com/banto6/haier/assets/80599145/79eee7df-9c9a-406d-8dda-9aecff64851e">
<img width="1222" alt="image" src="https://github.com/banto6/haier/assets/80599145/df5d6f22-e3c2-46e2-8340-5da4f73a64b2">
因此尝试提供能获取到的信息，看看是否有帮助。
另希望确认一下，是否HA内需要有其他设置才能看到设备信息？

2023-08-22 18:38:19.610 DEBUG (MainThread) [custom_components.haier.coordinator] 设备[0025922158C3]已获取到最新状态数据: {"intelligenceStatus": "false", "humidificationStatus": "false", "silentSleepStatus": "false", "electricHeatingStatus": "false", "ch2oValue": "0", "rapidMode": "false", "specialMode": "0", "10degreeHeatingStatus": "false", "ch2oCleaningStatus": "false", "humanSensingStatus": "0", "outdoorPM2p5Value": "0", "acType": "0", "lightStatus": "false", "totalCleaningTime": "0", "errCode": "0", "sensingResult": "0", "tempUnit": "1", "windDirectionVerticalL": "1", "lockStatus": "false", "selfCleaningStatus": "false", "airQuality": "0", "operationMode": "1", "co2Value": "0", "targetTemperature": "23", "vocValue": "0", "localFilterChangeFlag": "false", "energySavingStatus": "false", "freshAirStatus": "false", "windDirectionHorizontalR": "7", "onOffStatus": "false", "windDirectionVerticalR": "1", "halfDegreeSettingStatus": "false", "echoStatus": "true", "outdoorTemperature": "-64", "windDirectionHorizontalL": "7", "pm2p5Level": "0", "alarmCancel": "\u544a\u8b66\u89e3\u9664", "indoorPM2p5Value": "0", "windSpeedR": "5", "pmvStatus": "false", "muteStatus": "false", "healthMode": "false", "ErrAckFlag": "false", "pm2p5CleaningStatus": "false", "targetHumidity": "50", "indoorTemperature": "28", "opSrc": "1", "screenDisplayStatus": "false", "windSpeedL": "5", "indoorHumidity": "89"}
2023-08-22 18:38:19.610 DEBUG (MainThread) [custom_components.haier.coordinator] Finished fetching Haier Device [0025922158C3] data in 0.188 seconds (success: True)

**错误日志**
找到一个和空调有关的错误信息，不知是否有用？
2023-08-22 18:38:19.595 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 229, in _handle_refresh_interval
await self._async_refresh(log_failures=True, scheduled=True)
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 374, in _async_refresh
self.async_update_listeners()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in async_update_listeners
update_callback()
File "/config/custom_components/haier/entity.py", line 47, in _handle_coordinator_update
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 746, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 808, in _async_write_ha_state
state = self._stringify_state(available)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 752, in _stringify_state
if (state := self.state) is None:
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 573, in state
raise ValueError(
ValueError: Sensor sensor.0025922158c3_errcode provides state value '0', which is not in the list of options provided

**Comment by banto6** [comment]
因为该设备分左右风区造成的，我后期优化一下

**Comment by banto6** [comment]
已做兼容处理 https://github.com/banto6/haier/commit/125ba259fbc51520c2c2017ed7d9ad58230b695c 

可以使用master分支代码测试一下功能是否正常

**Comment by Loyido** [comment]
已修复，感谢
