### ISSUE TITLE
有一台空调不能正确识别

### ISSUE THREAD

**Issue by Xi11-github** [banto6/haier#6]
型号为：KFR-35G/WEC21AU1

**Comment by Xi11-github** [comment]
对的，日志文件显示初始化失败。
2023-07-04 09:06:26.634 ERROR (MainThread) [custom_components.haier] 设备[DC330D23E268]初始化失败

**Comment by Xi11-github** [comment]
2023-07-04 09:06:26.200 DEBUG (MainThread) [custom_components.haier] Device Info: {"deviceId": "DC330D23E268", "deviceName": "\u4e3b\u5367\u7a7a\u8c03", "deviceType": "03001001", "online": true, "permissions": [{"auth": {"control": true, "set": true, "view": true}, "authType": "owner"}, {"auth": {"control": true, "set": false, "view": true}, "authType": "home"}], "productCodeT": "AA9KTB015", "productNameT": "KFR-35G/WEC21AU1\u5ba4\u5185\u673a\u603b\u6210", "totalPermission": {"control": true, "set": true, "view": true}, "wifiType": "00000000000000008080000000041410"}
2023-07-04 09:06:26.634 ERROR (MainThread) [custom_components.haier] 设备[DC330D23E268]初始化失败

**Comment by Xi11-github** [comment]
好的，感谢！

**Comment by pangjian** [comment]
我有一个卡萨帝洗衣机也不能识别，型号HDU85G3

2023-07-04 14:40:27.056 DEBUG (MainThread) [custom_components.haier] Device Info: {"deviceId": "0007A8AAE287", "deviceName": "\u6d17\u8863\u673a", "deviceType": "05001009", "online": true, "permissions": [{"auth": {"control": true, "set": true, "view": true}, "authType": "owner"}, {"auth": {"control": true, "set": false, "view": true}, "authType": "home"}], "productCodeT": "CEAAJ0017", "productNameT": "C1 HDU85G3", "totalPermission": {"control": true, "set": true, "view": true}, "wifiType": "101c12002400081005010021800067000000f300000000000000000000000000"}

2023-07-04 14:40:28.167 ERROR (MainThread) [custom_components.haier] 设备[0007A8AAE287]初始化失败
Traceback (most recent call last):
  File "/config/custom_components/haier/__init__.py", line 34, in async_setup_entry
    coordinator = await new_device_coordinator(hass, client, device)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/__init__.py", line 78, in new_device_coordinator
    device['config'] = await client.get_hardware_config(device['wifiType'])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/haier.py", line 142, in get_hardware_config
    if 'data' not in content or 'url' not in content['data']:
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable

**Comment by banto6** [comment]
> 我有一个卡萨帝洗衣机也不能识别，型号HDU85G3
> 
> 2023-07-04 14:40:27.056 DEBUG (MainThread) [custom_components.haier] Device Info: {"deviceId": "0007A8AAE287", "deviceName": "\u6d17\u8863\u673a", "deviceType": "05001009", "online": true, "permissions": [{"auth": {"control": true, "set": true, "view": true}, "authType": "owner"}, {"auth": {"control": true, "set": false, "view": true}, "authType": "home"}], "productCodeT": "CEAAJ0017", "productNameT": "C1 HDU85G3", "totalPermission": {"control": true, "set": true, "view": true}, "wifiType": "101c12002400081005010021800067000000f300000000000000000000000000"}
> 
> 2023-07-04 14:40:28.167 ERROR (MainThread) [custom_components.haier] 设备[0007A8AAE287]初始化失败 Traceback (most recent call last): File "/config/custom_components/haier/**init**.py", line 34, in async_setup_entry coordinator = await new_device_coordinator(hass, client, device) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/haier/**init**.py", line 78, in new_device_coordinator device['config'] = await client.get_hardware_config(device['wifiType']) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/haier/haier.py", line 142, in get_hardware_config if 'data' not in content or 'url' not in content['data']: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ TypeError: argument of type 'NoneType' is not iterable

海尔智家APP中可以正常使用吗？刚测试使用APP的API拉取这个设备的配置文件也失败了

**Comment by Xi11-github** [comment]
刚在Hassbian论坛看到一个坛友说，微信小程序里面没有的设备，在这个插件上也没有，我看了一了我也是相同的情况。

**Comment by pangjian** [comment]
> 在智家App可以正常使用

**Comment by Xi11-github** [comment]
对，智家APP正常。可能API接口不同，微信小程序上有提示：小程序暂不支持所有设备，若您未在当前家庭下找到设备，请耐心等待，我们会尽快处理

**Comment by Xi11-github** [comment]
问了海尔客服，智家小程序尚在开发种，功能不完善，有些设备不能显示

**Comment by csl0918** [comment]
奇怪,我的一台卡萨帝的冰箱在微信小程序中能够显示,但是也无法识别呢,

**Comment by banto6** [comment]
> 奇怪,我的一台卡萨帝的冰箱在微信小程序中能够显示,但是也无法识别呢,

项目使用的不是微信小程序的接口，所以不能保证小程序能识别的本项目就能识别，不能识别的问题后续会尝试更换接口
