### ISSUE TITLE
可以识别卡萨帝冰箱，不能识别海尔中央空调

### ISSUE THREAD

**Issue by yefei** [banto6/haier#7]
首先非常感谢作者开发这个插件！

卡萨帝冰箱识别的挺好，功能挺全。 就是海尔的中央空调没有识别到，我只能在手机app里控制。

**Comment by yefei** [comment]
2023-07-04 09:11:11.297 ERROR (MainThread) [custom_components.haier] 设备[3429EF023D80]初始化失败
Traceback (most recent call last):
File "/config/custom_components/haier/__init__.py", line 34, in async_setup_entry
coordinator = await new_device_coordinator(hass, client, device)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/haier/__init__.py", line 78, in new_device_coordinator
device['config'] = await client.get_hardware_config(device['wifiType'])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/haier/haier.py", line 142, in get_hardware_config
if 'data' not in content or 'url' not in content['data']:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable

**Comment by yefei** [comment]
```
2023-07-04 09:28:41.618 DEBUG (MainThread) [custom_components.haier.coordinator] 设备[1457909B6F30]已获取到最新状态数据: {"quickRefrigeratingMode": "false", "frzSterilizationOffTime": "73", "vtRoomDoorStatus": "false", "vtRoomTemperature": "-18", "frzSterilizationForcedOn": "false", "refSterilizationModuleStatus": "true", "travelMode": "false", "dailyStatus": "true", "envTemperature": "29", "refSterilizationForcedOff": "false", "refrigeratorDoorStatus": "false", "envHumidity": "85", "frzSterilizationForcedOff": "false", "humanSensingStatus": "true", "frzSterilizationModuleStatus": "false", "freezerTemperatureC": "-18", "freezerDoorStatus": "false", "humanSensingResult": "0", "vtRoom2TargetTempLevel": "31", "cellPreservationStatus": "false", "refSterilizationForcedOn": "true", "freezerTargetTempLevel": "12", "refrigeratorTargetTempLevel": "6", "refrigeratorTemperatureC": "5", "intelligenceMode": "false", "quickFreezingMode": "false", "vtRoomTargetTempLevel": "13", "vastStoreStatus": "false", "sterilizationTime": "349", "refSterilizationOffTime": "0", "refSmellSensorValue": "0", "frzSterilizationTime": "355"}
2023-07-04 09:28:41.618 DEBUG (MainThread) [custom_components.haier.coordinator] Finished fetching Haier Device [1457909B6F30] data in 0.219 seconds (success: True)
```
