### ISSUE TITLE
海尔风管机请求能更新以支持

### ISSUE THREAD

**Issue by roycho93** [banto6/haier#70]
**问题描述**
海尔智家中的风管机无法被识别到，提示没有设备或实体。如有可能，希望能更新以支持，不胜感激。
更新一下，才看到错误日志怎么查看，这里面的获取配置文件失败就是置顶issue中提到的需要等待api更新对吧？如有重复提交还请见谅。

**环境信息:**
 - Homeassistant版本: [e.g. 2023.12.1]

**设备信息**
若是设备无法识别或控制错误则此项**必填**。
海尔智家中设备管理查看的设备型号为 SKFR-72L/WAA22A(茉莉白)室内机总成
以下信息开启debug模式后可在`Device Info`部分的日志中找到。日志可在`配置 > 系统 > 日志 > 加载完整日志`中查看。
```
deviceType:03001001
productCodeT:AB90V5007
productNameT:SKFR-72L/WAA22A(茉莉白)室内机总成
wifiType:00000000000000008080000000041410
```

**错误日志**
2023-12-13 09:43:30.152 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration ha_cloud_music which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-13 09:43:30.155 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration ha_file_explorer which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-13 09:43:30.159 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration haier which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-13 09:43:30.162 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration hacs_proxy which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-13 09:43:30.165 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration midea_ac_lan which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-13 09:43:30.168 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration yeelight_pro which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-13 09:43:30.171 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration xiaomi_miot which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-13 09:43:30.174 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration sonoff which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-13 09:43:30.177 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration localtuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-13 09:43:30.180 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration xiaomi_gateway3 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-13 09:43:30.182 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-13 09:44:07.026 ERROR (MainThread) [custom_components.haier.core.client] 获取配置信息失败, wifi_type: 00000000000000008080000000041410, response: {"status": "1", "data": null, "total": 0}
2023-12-13 09:44:07.208 ERROR (MainThread) [custom_components.haier.core.device] 获取attributes失败
Traceback (most recent call last):
  File "/config/custom_components/haier/core/device.py", line 72, in async_init
    properties = (await self._client.get_hardware_config(self.wifi_type))['Property']
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/core/client.py", line 190, in get_hardware_config
    raise HaierClientException('获取配置文件失败')
custom_components.haier.core.client.HaierClientException: 获取配置文件失败
2023-12-13 09:44:08.709 ERROR (MainThread) [custom_components.haier.core.client] 获取配置信息失败, wifi_type: 00000000000000008080000000041410, response: {"status": "1", "data": null, "total": 0}
2023-12-13 09:44:08.712 ERROR (MainThread) [custom_components.haier.core.device] 获取attributes失败
Traceback (most recent call last):
  File "/config/custom_components/haier/core/device.py", line 72, in async_init
    properties = (await self._client.get_hardware_config(self.wifi_type))['Property']
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/core/client.py", line 190, in get_hardware_config
    raise HaierClientException('获取配置文件失败')
custom_components.haier.core.client.HaierClientException: 获取配置文件失败
2023-12-13 09:44:10.727 ERROR (MainThread) [custom_components.haier.core.client] 获取配置信息失败, wifi_type: 00000000000000008080000000041410, response: {"status": "1", "data": null, "total": 0}
2023-12-13 09:44:10.799 ERROR (MainThread) [custom_components.haier.core.device] 获取attributes失败
Traceback (most recent call last):
  File "/config/custom_components/haier/core/device.py", line 72, in async_init
    properties = (await self._client.get_hardware_config(self.wifi_type))['Property']
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/core/client.py", line 190, in get_hardware_config
    raise HaierClientException('获取配置文件失败')
custom_components.haier.core.client.HaierClientException: 获取配置文件失败
2023-12-13 09:44:11.426 ERROR (MainThread) [custom_components.haier.core.client] 获取配置信息失败, wifi_type: 00000000000000008080000000041410, response: {"status": "1", "data": null, "total": 0}
2023-12-13 09:44:11.430 ERROR (MainThread) [custom_components.haier.core.device] 获取attributes失败
Traceback (most recent call last):
  File "/config/custom_components/haier/core/device.py", line 72, in async_init
    properties = (await self._client.get_hardware_config(self.wifi_type))['Property']
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/core/client.py", line 190, in get_hardware_config
    raise HaierClientException('获取配置文件失败')
custom_components.haier.core.client.HaierClientException: 获取配置文件失败
2023-12-13 09:44:11.920 ERROR (MainThread) [custom_components.haier.core.client] 获取配置信息失败, wifi_type: 00000000000000008080000000041410, response: {"status": "1", "data": null, "total": 0}
2023-12-13 09:44:11.923 ERROR (MainThread) [custom_components.haier.core.device] 获取attributes失败
Traceback (most recent call last):
  File "/config/custom_components/haier/core/device.py", line 72, in async_init
    properties = (await self._client.get_hardware_config(self.wifi_type))['Property']
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/core/client.py", line 190, in get_hardware_config
    raise HaierClientException('获取配置文件失败')
custom_components.haier.core.client.HaierClientException: 获取配置文件失败
2023-12-13 09:44:12.338 ERROR (MainThread) [custom_components.haier.core.client] 获取配置信息失败, wifi_type: 00000000000000008080000000041410, response: {"status": "1", "data": null, "total": 0}
2023-12-13 09:44:12.341 ERROR (MainThread) [custom_components.haier.core.device] 获取attributes失败
Traceback (most recent call last):
  File "/config/custom_components/haier/core/device.py", line 72, in async_init
    properties = (await self._client.get_hardware_config(self.wifi_type))['Property']
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/core/client.py", line 190, in get_hardware_config
    raise HaierClientException('获取配置文件失败')
custom_components.haier.core.client.HaierClientException: 获取配置文件失败
2023-12-13 09:44:12.352 ERROR (MainThread) [custom_components.haier] Device [0007A8C16094] 未获取到可用attribute
2023-12-13 09:44:12.352 ERROR (MainThread) [custom_components.haier] Device [0007A8D80AA3] 未获取到可用attribute
2023-12-13 09:44:12.353 ERROR (MainThread) [custom_components.haier] Device [0007A8CA2670] 未获取到可用attribute
2023-12-13 09:44:12.353 ERROR (MainThread) [custom_components.haier] Device [0007A8C09D36] 未获取到可用attribute
2023-12-13 09:44:12.354 ERROR (MainThread) [custom_components.haier] Device [0007A8BEAF0B] 未获取到可用attribute
2023-12-13 09:44:12.354 ERROR (MainThread) [custom_components.haier] Device [0007A8CA2675] 未获取到可用attribute

**Comment by banto6** [comment]
获取配置文件失败 表示API不支持该设备， 逆向海尔智家APP遇到了一些阻碍，所以暂时无解。
