### ISSUE TITLE
洗衣机识别出错

### ISSUE THREAD

**Issue by caoailin** [banto6/haier#71]
调试信息
2023-12-18 11:11:49.913 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration tcl_tv_remote which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-18 11:11:49.917 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration bemfa which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-18 11:11:49.922 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-18 11:11:49.925 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration hon which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-18 11:11:49.929 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration midea_ac_lan which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-18 11:11:49.932 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration haier which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-18 11:12:15.980 ERROR (MainThread) [custom_components.haier.core.client] 获取配置信息失败, wifi_type: 111c120024000810050100218001154300006400000000000000000000000000, response: {"status": "1", "data": null, "total": 0}
2023-12-18 11:12:16.009 ERROR (MainThread) [custom_components.haier.core.device] 获取attributes失败
Traceback (most recent call last):
  File "/config/custom_components/haier/core/device.py", line 72, in async_init
    properties = (await self._client.get_hardware_config(self.wifi_type))['Property']
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/core/client.py", line 190, in get_hardware_config
    raise HaierClientException('获取配置文件失败')
custom_components.haier.core.client.HaierClientException: 获取配置文件失败
2023-12-18 11:12:16.023 ERROR (MainThread) [custom_components.haier] Device [DC330DAC827F] 未获取到可用attribute
2023-12-18 11:12:19.088 WARNING (SyncWorker_5) [pyroute2.netlink.rtnl.tcmsg.common] tcmsg: [Errno 2] No such file or directory: '/proc/net/psched'
2023-12-18 11:12:19.127 WARNING (SyncWorker_5) [pyroute2.netlink.rtnl.tcmsg.common] the tc subsystem functionality is limited
2023-12-18 11:13:39.411 DEBUG (MainThread) [custom_components.haier] 已从HomeAssistant加载到缓存的token
2023-12-18 11:13:39.766 DEBUG (MainThread) [custom_components.haier.core.client] Device Info: {'deviceId': 'DC330DAC827F', 'deviceName': '滚筒洗衣机827F', 'deviceType': '0500102B', 'online': True, 'permissions': [{'auth': {'control': True, 'set': True, 'view': True}, 'authType': 'owner'}], 'productCodeT': 'CE0JK7017', 'productNameT': 'EG8014HB39GU1', 'totalPermission': {'control': True, 'set': True, 'view': True}, 'wifiType': '111c120024000810050100218001154300006400000000000000000000000000'}
2023-12-18 11:13:40.296 ERROR (MainThread) [custom_components.haier.core.client] 获取配置信息失败, wifi_type: 111c120024000810050100218001154300006400000000000000000000000000, response: {"status": "1", "data": null, "total": 0}
2023-12-18 11:13:40.313 ERROR (MainThread) [custom_components.haier.core.device] 获取attributes失败
Traceback (most recent call last):
  File "/config/custom_components/haier/core/device.py", line 72, in async_init
    properties = (await self._client.get_hardware_config(self.wifi_type))['Property']
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/core/client.py", line 190, in get_hardware_config
    raise HaierClientException('获取配置文件失败')
custom_components.haier.core.client.HaierClientException: 获取配置文件失败
2023-12-18 11:13:40.325 ERROR (MainThread) [custom_components.haier] Device [DC330DAC827F] 未获取到可用attribute
2023-12-18 11:13:40.330 DEBUG (MainThread) [custom_components.haier] 共获取到0个设备

**Comment by banto6** [comment]
see https://github.com/banto6/haier/issues/34
