### ISSUE TITLE
调用服务 number/set_value 失败。 '<' not supported between instances of 'float' and 'str'

### ISSUE THREAD

**Issue by kkkkk5G** [banto6/haier#78]
**问题描述**
空调设置目标温度失败，提示调用服务 number/set_value 失败。 '<' not supported between instances of 'float' and 'str'

**环境信息:**
 - Homeassistant版本: [e.g. 2024.1.0]

**设备信息**
若是设备无法识别或控制错误则此项**必填**。

以下信息开启debug模式后可在`Device Info`部分的日志中找到。日志可在`配置 > 系统 > 日志 > 加载完整日志`中查看。
```
deviceType:0D02100c
productCodeT:AA9E5L001
productNameT:RFTS71MXS-D2
wifiType:True
```

**错误日志**
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:238
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 08:58:55 (3 occurrences)
Last logged: 09:05:56

[2652220072] '<' not supported between instances of 'float' and 'str'
[2939088360] '<' not supported between instances of 'float' and 'str'
Traceback (most recent call last):
  File "/home/homeassistant/source/homeassistant/lib/python3.11/site-packages/homeassistant/components/websocket_api/commands.py", line 238, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/source/homeassistant/lib/python3.11/site-packages/homeassistant/core.py", line 2173, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/home/homeassistant/source/homeassistant/lib/python3.11/site-packages/homeassistant/core.py", line 2210, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/source/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/entity_component.py", line 272, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/source/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/service.py", line 882, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/source/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/service.py", line 952, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/home/homeassistant/source/homeassistant/lib/python3.11/site-packages/homeassistant/components/number/__init__.py", line 100, in async_set_value
    if value < entity.min_value or value > entity.max_value:
       ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'float' and 'str'

**Comment by kkkkk5G** [comment]
同时发现在启动时也有关于类型的报错，我进行了如下改动可以解决启动时climate的报错；麻烦大佬看看是不是存在兼容问题？
![image](https://github.com/banto6/haier/assets/16422884/a34a7e7d-2b1e-4caa-afef-5f2617585834)

**Comment by banto6** [comment]
您好，修改后没问题的话欢迎PR

**Comment by kkkkk5G** [comment]
> 您好，修改后没问题的话欢迎PR

大佬review过了吗？那我提交了哈

**Comment by banto6** [comment]
从代码上来看没有问题，不过我本地没有海尔的空调设备，你测试没问题提交就行

**Comment by kkkkk5G** [comment]
> 从代码上来看没有问题，不过我本地没有海尔的空调设备，你测试没问题提交就行

已自测；pr已提交；issue关了哈

**Comment by banto6** [comment]
https://github.com/banto6/haier/pull/79 PR已合并
