### ISSUE TITLE
4台空调只识别出1台

### ISSUE THREAD

**Issue by regomne** [banto6/haier#82]
**问题描述**

4台空调设备只识别出了一台。

**环境信息:**
 - Homeassistant版本: 2024.1.5

**设备信息**

3台没识别出来的的设备信息类似，都是03001001的。

```
deviceType: 03001001
productCodeT: AB91SB06N
productNameT: KFR-50L/FBA21AU1室内机总成
wifiType: 00000000000000008080000000041410
```

**错误日志**

```
2024-01-25 10:09:12.690 DEBUG (MainThread) [custom_components.haier.core.client] Device Info: {'deviceId': 'DC330DB9D5CF', 'deviceName': '立式空调', 'deviceType': '03001001', 'online': True, 'permissions': [{'auth': {'control': True, 'set': True, 'view': True}, 'authType': 'owner'}, {'auth': {'control': True, 'set': False, 'view': True}, 'authType': 'home'}], 'productCodeT': 'AB91SB06N', 'productNameT': 'KFR-50L/FBA21AU1室内机总成', 'totalPermission': {'control': True, 'set': True, 'view': True}, 'wifiType': '00000000000000008080000000041410'}
2024-01-25 10:09:13.186 ERROR (MainThread) [custom_components.haier.core.client] 获取配置信息失败, wifi_type: 00000000000000008080000000041410, response: {"status": "1", "data": null, "total": 0}
2024-01-25 10:09:13.187 ERROR (MainThread) [custom_components.haier.core.device] 获取attributes失败
Traceback (most recent call last):
  File "/config/custom_components/haier/core/device.py", line 72, in async_init
    properties = (await self._client.get_hardware_config(self.wifi_type))['Property']
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/core/client.py", line 190, in get_hardware_config
    raise HaierClientException('获取配置文件失败')
custom_components.haier.core.client.HaierClientException: 获取配置文件失败
```

**Comment by regomne** [comment]
好吧是api版本的问题，先关闭了。我自己也逆一下试试。
