### ISSUE TITLE
实体里面找不到海尔空调

### ISSUE THREAD

**Issue by pigdogkiki** [banto6/haier#90]
**问题描述**

**环境信息:**
 - Homeassistant版本: [e.g. 2023.6.2]

**设备信息**
若是设备无法识别或控制错误则此项**必填**。

以下信息开启debug模式后可在`Device Info`部分的日志中找到。日志可在`配置 > 系统 > 日志 > 加载完整日志`中查看。
```
deviceType:
productCodeT:
productNameT:
wifiType:
```

**错误日志**

**Comment by banto6** [comment]
请提供集成日志

**Comment by vai551234** [comment]
你好，我也是找不到空调。我是纯小白，请问在哪里可以找到集成日志

**Comment by iamhaifeng** [comment]
Homeassistant版本: 2024.2.2
本插件版本：0.1.3

登陆海尔账号后未发现任何实体，我的账号中本来有海尔冰箱和海尔中央空调。以下是日志：

2024-03-12 11:00:48.134 ERROR (MainThread) [custom_components.haier.core.client] 获取配置信息失败, wifi_type: 01c12002400081034080000000100000, response: {"status": "1", "data": null, "total": 0}
2024-03-12 11:00:48.140 ERROR (MainThread) [custom_components.haier.core.device] 获取attributes失败
Traceback (most recent call last):
  File "/config/custom_components/haier/core/device.py", line 72, in async_init
    properties = (await self._client.get_hardware_config(self.wifi_type))['Property']
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/core/client.py", line 190, in get_hardware_config
    raise HaierClientException('获取配置文件失败')
custom_components.haier.core.client.HaierClientException: 获取配置文件失败
2024-03-12 11:00:48.578 ERROR (MainThread) [custom_components.haier.core.client] 获取配置信息失败, wifi_type: 01c12002400081034080000000100000, response: {"status": "1", "data": null, "total": 0}
2024-03-12 11:00:48.581 ERROR (MainThread) [custom_components.haier.core.device] 获取attributes失败
Traceback (most recent call last):
  File "/config/custom_components/haier/core/device.py", line 72, in async_init
    properties = (await self._client.get_hardware_config(self.wifi_type))['Property']
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/core/client.py", line 190, in get_hardware_config
    raise HaierClientException('获取配置文件失败')
custom_components.haier.core.client.HaierClientException: 获取配置文件失败
2024-03-12 11:00:49.031 ERROR (MainThread) [custom_components.haier.core.client] 获取配置信息失败, wifi_type: 01c12002400081034080000000100000, response: {"status": "1", "data": null, "total": 0}
2024-03-12 11:00:49.037 ERROR (MainThread) [custom_components.haier.core.device] 获取attributes失败
Traceback (most recent call last):
  File "/config/custom_components/haier/core/device.py", line 72, in async_init
    properties = (await self._client.get_hardware_config(self.wifi_type))['Property']
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/core/client.py", line 190, in get_hardware_config
    raise HaierClientException('获取配置文件失败')
custom_components.haier.core.client.HaierClientException: 获取配置文件失败
2024-03-12 11:00:49.466 ERROR (MainThread) [custom_components.haier.core.client] 获取配置信息失败, wifi_type: 01c12002400081034080000000100000, response: {"status": "1", "data": null, "total": 0}
2024-03-12 11:00:49.469 ERROR (MainThread) [custom_components.haier.core.device] 获取attributes失败
Traceback (most recent call last):
  File "/config/custom_components/haier/core/device.py", line 72, in async_init
    properties = (await self._client.get_hardware_config(self.wifi_type))['Property']
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/core/client.py", line 190, in get_hardware_config
    raise HaierClientException('获取配置文件失败')
custom_components.haier.core.client.HaierClientException: 获取配置文件失败
2024-03-12 11:00:49.886 ERROR (MainThread) [custom_components.haier.core.client] 获取配置信息失败, wifi_type: 01c12002400081034080000000100000, response: {"status": "1", "data": null, "total": 0}
2024-03-12 11:00:49.891 ERROR (MainThread) [custom_components.haier.core.device] 获取attributes失败
Traceback (most recent call last):
  File "/config/custom_components/haier/core/device.py", line 72, in async_init
    properties = (await self._client.get_hardware_config(self.wifi_type))['Property']
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/core/client.py", line 190, in get_hardware_config
    raise HaierClientException('获取配置文件失败')
custom_components.haier.core.client.HaierClientException: 获取配置文件失败
2024-03-12 11:00:50.318 ERROR (MainThread) [custom_components.haier.core.client] 获取配置信息失败, wifi_type: 00000000000000008080000000041410, response: {"status": "1", "data": null, "total": 0}
2024-03-12 11:00:50.321 ERROR (MainThread) [custom_components.haier.core.device] 获取attributes失败
Traceback (most recent call last):
  File "/config/custom_components/haier/core/device.py", line 72, in async_init
    properties = (await self._client.get_hardware_config(self.wifi_type))['Property']
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/core/client.py", line 190, in get_hardware_config
    raise HaierClientException('获取配置文件失败')
custom_components.haier.core.client.HaierClientException: 获取配置文件失败
2024-03-12 11:00:50.754 ERROR (MainThread) [custom_components.haier.core.client] 获取配置信息失败, wifi_type: 111c120024000810010400618003474300000000000061800312430000000000, response: {"status": "1", "data": null, "total": 0}
2024-03-12 11:00:50.759 ERROR (MainThread) [custom_components.haier.core.device] 获取attributes失败
Traceback (most recent call last):
  File "/config/custom_components/haier/core/device.py", line 72, in async_init
    properties = (await self._client.get_hardware_config(self.wifi_type))['Property']
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/core/client.py", line 190, in get_hardware_config
    raise HaierClientException('获取配置文件失败')
custom_components.haier.core.client.HaierClientException: 获取配置文件失败
2024-03-12 11:00:50.767 ERROR (MainThread) [custom_components.haier] Device [04FA831EDE65_1-4] 未获取到可用attribute
2024-03-12 11:00:50.768 ERROR (MainThread) [custom_components.haier] Device [04FA831EDE65_1-5] 未获取到可用attribute
2024-03-12 11:00:50.769 ERROR (MainThread) [custom_components.haier] Device [04FA831EDE65_1-2] 未获取到可用attribute
2024-03-12 11:00:50.770 ERROR (MainThread) [custom_components.haier] Device [04FA831EDE65_1-3] 未获取到可用attribute
2024-03-12 11:00:50.771 ERROR (MainThread) [custom_components.haier] Device [04FA831EDE65_1-1] 未获取到可用attribute
2024-03-12 11:00:50.772 ERROR (MainThread) [custom_components.haier] Device [DC330DCDBF25] 未获取到可用attribute
2024-03-12 11:00:50.775 ERROR (MainThread) [custom_components.haier] Device [18A7F1B3DBBA] 未获取到可用attribute

**Comment by banto6** [comment]
see https://github.com/banto6/haier/issues/34
