### ISSUE TITLE
每隔一到两天就会失效， 需要重新载入

### ISSUE THREAD

**Issue by Jay-HomeAssistant** [banto6/haier#95]
**问题描述**
请教下，我遇到的问题是大约每隔一到两天就会显示“设置失败”，如附图，需要手动做重新载入才能继续正常使用. 
非常感谢！
![屏幕截图 2024-03-27 233156](https://github.com/banto6/haier/assets/151174820/54f8b3da-f427-4ac5-ac96-5461dfe4e60f)

**环境信息:**
 - Homeassistant版本: [e.g. 2023.6.2]
2023.11.2

**设备信息**
-应该与设备无关； 我的设备是海尔KN3热水器，有设定HA的自动化利用实体开关去控制零冷水的开关

以下信息开启debug模式后可在`Device Info`部分的日志中找到。日志可在`配置 > 系统 > 日志 > 加载完整日志`中查看。
```
deviceType:
productCodeT:
productNameT:
wifiType:
```

**错误日志**
Logger: homeassistant.config_entries
Source: config_entries.py:402
First occurred: 18:29:01 (1 occurrences)
Last logged: 18:29:01

Error setting up entry Haier: for haier
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1112, in create_connection
    transport, protocol = await self._create_connection_transport(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1145, in _create_connection_transport
    await waiter
  File "/usr/local/lib/python3.11/asyncio/sslproto.py", line 575, in _on_handshake_complete
    raise handshake_exc
ConnectionResetError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/__init__.py", line 62, in async_setup_entry
    devices = await get_available_devices(client)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/__init__.py", line 133, in get_available_devices
    devices = await client.get_devices() + await get_virtual_devices(client)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/core/client.py", line 118, in get_devices
    async with http_client.get(url=GET_DEVICES_API, headers=headers) as response:
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1209, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1178, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host uws.haier.net:443 ssl:default [None]

![屏幕截图 2024-03-27 234155](https://github.com/banto6/haier/assets/151174820/bd3b9d22-bf70-440f-844b-5c5f14a763d6)

**Comment by Jay-HomeAssistant** [comment]
抱歉刚刚才开启调试模式，我再等它失效后将log上传，谢谢

**Comment by banto6** [comment]
**_aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host uws.haier.net:443 ssl:default [None]_**

网络问题，没办法访问uws.haier.net，检查一下网络环境
